import {enhancementClient} from './enhancement-client.js';
import {reviewNote,resultMatches,unicodeChanges,normalizePreferences,normalizeProfile,orderedOcrLines,migrateReviews,moveRegionGroup} from './enhancement-tools.js';
import {uxClient} from './ux-client.js';
import {reviewOverview,batchReadiness,fitScale,comparisonArea,editCheckpoint,editStep} from './ux-tools.js';
import {targetSignature,validateWorkspace} from './workspace-state.js';
import {featureClient} from './feature-client.js';
import {reviewSignature,manualState,reportRows,excelAssignments,excludedLine,csvReport} from './feature-tools.js';
import {workbenchClient} from './workbench-client.js';
import {imageSummary,transformRegion} from './workbench-tools.js';
import {workspaceClient} from './workspace-client.js';
import {workspaceUpgrade} from './workspace-upgrade.js';
import {workspaceMatches,regionCopy} from './workspace-tools.js';
import {sharedRegion,restoreRegionResult} from './region-analysis.js';
export const clientSource=String.raw`(()=>{'use strict';
${[reviewNote,resultMatches,unicodeChanges,normalizePreferences,normalizeProfile,orderedOcrLines,migrateReviews,moveRegionGroup,reviewSignature,manualState,reportRows,excelAssignments,excludedLine,csvReport].map(fn=>fn.toString()).join('\n')}
${[reviewOverview,batchReadiness,fitScale,comparisonArea,editCheckpoint,editStep].map(fn=>fn.toString()).join('\n')}
${imageSummary.toString()}
${transformRegion.toString()}
${workspaceMatches.toString()}
${regionCopy.toString()}
${targetSignature.toString()}
${validateWorkspace.toString()}
${sharedRegion.toString()}
${restoreRegionResult.toString()}
const L=window.LINGUALENS_LANGUAGES,$=id=>document.getElementById(id),S={n:0,url:'',resultUrl:'',historyUrls:[],book:null,rows:[],mapped:[],select:null,start:null,controller:null,last:null,targets:[],zoom:1,focus:false,connected:false};
const esc=v=>String(v??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[c]));
const opts=selected=>L.map(x=>'<option value="'+x.id+'"'+(x.id===selected?' selected':'')+'>'+esc(x.label)+' ('+x.id+')</option>').join('');
const HISTORY_DB='lingualens-local',HISTORY_STORE='history',HISTORY_LIMIT=10;
function historyDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(HISTORY_DB,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(HISTORY_STORE))db.createObjectStore(HISTORY_STORE,{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function historyAll(){const db=await historyDb();return new Promise((resolve,reject)=>{const transaction=db.transaction(HISTORY_STORE,'readonly'),request=transaction.objectStore(HISTORY_STORE).getAll();request.onsuccess=()=>resolve(request.result.sort((a,b)=>String(b.at).localeCompare(String(a.at))));request.onerror=()=>reject(request.error);transaction.oncomplete=()=>db.close()})}
async function historyPut(record){const db=await historyDb();await new Promise((resolve,reject)=>{const transaction=db.transaction(HISTORY_STORE,'readwrite');transaction.objectStore(HISTORY_STORE).put(record);transaction.oncomplete=resolve;transaction.onerror=()=>reject(transaction.error)});db.close()}
async function historyDelete(ids){if(!ids.length)return;const db=await historyDb();await new Promise((resolve,reject)=>{const transaction=db.transaction(HISTORY_STORE,'readwrite'),store=transaction.objectStore(HISTORY_STORE);ids.forEach(id=>store.delete(id));transaction.oncomplete=resolve;transaction.onerror=()=>reject(transaction.error)});db.close()}
async function historyClear(){const db=await historyDb();await new Promise((resolve,reject)=>{const transaction=db.transaction(HISTORY_STORE,'readwrite');transaction.objectStore(HISTORY_STORE).clear();transaction.oncomplete=resolve;transaction.onerror=()=>reject(transaction.error)});db.close()}
async function historyImage(file){try{const bitmap=await createImageBitmap(file),scale=Math.min(1,1280/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d',{alpha:false}).drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.78));return blob||file}catch{return file.size<=3145728?file:null}}
async function ocrImage(file){try{const bitmap=await createImageBitmap(file),longSide=Math.max(bitmap.width,bitmap.height);if(longSide<=2200&&file.size<=2621440){bitmap.close();return file}const scale=Math.min(1,2200/longSide),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d',{alpha:false}).drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.9));if(!blob||blob.size>=file.size)return file;return new File([blob],file.name.replace(/\.[^.]+$/,'.webp'),{type:'image/webp',lastModified:file.lastModified})}catch{return file}}
function resetResult(){if(S.controller)S.controller.abort();S.last=null;S.targets=[];if(S.resultUrl){URL.revokeObjectURL(S.resultUrl);S.resultUrl=''}$('resultCard').classList.add('hidden');$('resultImage').removeAttribute('src');$('resultBoxes').innerHTML='';$('results').innerHTML='';$('summary').innerHTML='';$('ocrText').textContent='';$('statusResult').textContent='검증 전';document.querySelectorAll('.filter').forEach(button=>button.classList.toggle('active',button.dataset.filter==='all'));progress(false);$('run').disabled=false;$('run').textContent='검증 시작';step(2);if(UI?.ready){$('canvasEvidence').replaceChildren();setWorkbenchTab('settings');refreshWorkbench()}}
function error(message){$('globalError').textContent=message||'';$('globalError').classList.toggle('hidden',!message);if(message)$('globalError').scrollIntoView({behavior:'smooth',block:'center'})}
function step(number){document.querySelectorAll('.steps li').forEach(item=>item.classList.toggle('active',+item.dataset.step<=number))}
const help=mode=>mode==='required'?'입력한 모든 글자가 있어야 합니다. 띄어쓰기와 줄바꿈은 비교에서 제외합니다.':'대소문자·기호·띄어쓰기는 그대로 확인하고, 화면 폭에 따른 자동 줄바꿈은 허용합니다.';
const rtext=region=>region?'영역 '+[region.x,region.y,region.width,region.height].map(x=>Math.round(x*1000)/1000).join(', '):'전체 화면에서 찾기';
function read(row){let region=null;try{region=row.dataset.region?JSON.parse(row.dataset.region):null}catch{}return{id:row.dataset.id,label:row.querySelector('.entry-label').value.trim(),language:row.querySelector('.language').value,mode:row.querySelector('.mode').value,text:row.querySelector('.phrase').value.replace(/\r\n?/g,'\n'),region,locked:row.dataset.locked==='true',hidden:row.dataset.hidden==='true'}}
function syncRegion(row,region){if(region)row.dataset.region=JSON.stringify(region);else delete row.dataset.region;row.querySelector('.region-status').textContent=rtext(region);['x','y','width','height'].forEach(key=>{const input=row.querySelector('[data-coordinate="'+key+'"]');if(input)input.value=region?Math.round(region[key]*1000)/1000:''});regions()}
function refresh(){const rows=[...document.querySelectorAll('.entry')];rows.forEach((row,index)=>{row.querySelector('.idx').textContent='검증 항목 '+(index+1);row.querySelector('.remove').disabled=rows.length===1});$('entryCount').textContent=rows.length+'개';$('statusEntries').textContent=rows.length+'개 항목';$('addEntry').disabled=rows.length>=80;regions()}
function add(data={}){
  if(document.querySelectorAll('.entry').length>=80)return;
  S.n++;const row=document.createElement('article');row.className='entry';row.dataset.locked=String(!!data.locked);row.dataset.hidden=String(!!data.hidden);row.dataset.id=data.id||crypto.randomUUID();
  row.innerHTML='<div class="entry-head"><div class="entry-title"><i class="entry-dot"></i><strong class="idx"></strong></div><div class="entry-actions"><button class="ghost small collapse" type="button">접기</button><button class="ghost small duplicate" type="button">복제</button><button class="danger small remove" type="button">삭제</button></div></div><div class="entry-body"><label>화면명 또는 ID <span class="optional">선택</span></label><input class="entry-label" maxlength="120" placeholder="예: 로그인 화면 / BTN_START"><div class="grid"><div><label>문구 언어</label><select class="language">'+opts(data.language||'ko')+'</select></div><div><label>입력 방식</label><select class="mode"><option value="exact">정확히 일치 · 자동 개행 허용</option><option value="required">모든 글자 포함 · 공백 무시</option></select></div></div><label>검증할 문구</label><textarea class="phrase" maxlength="3000" placeholder="확인할 문구를 입력하세요. 여러 줄도 입력할 수 있습니다."></textarea><div class="phrase-foot"><p class="help modehelp"></p><span class="char-count">0 / 3,000</span></div><div class="region-row"><span class="region-status"></span><button class="ghost small select-region" type="button">화면에서 지정</button><button class="ghost small clear-region" type="button">전체 화면</button></div><details class="region-editor"><summary>좌표 직접 편집</summary><div class="coordinate-grid">'+['x','y','width','height'].map(key=>'<label>'+key+'<input type="number" min="0" max="1" step="0.001" data-coordinate="'+key+'" placeholder="0.000"></label>').join('')+'</div><button class="ghost small apply-region" type="button">좌표 적용</button></details></div>';
  row.querySelector('.entry-label').value=data.label||'';row.querySelector('.phrase').value=data.text??'';row.querySelector('.mode').value=data.mode==='required'?'required':'exact';row.querySelector('.modehelp').textContent=help(row.querySelector('.mode').value);row.querySelector('.char-count').textContent=(data.text?.length||0).toLocaleString()+' / 3,000';
  row.querySelector('.mode').onchange=event=>row.querySelector('.modehelp').textContent=help(event.target.value);
  row.querySelector('.phrase').oninput=event=>{row.querySelector('.char-count').textContent=event.target.value.length.toLocaleString()+' / 3,000'};
  row.querySelector('.collapse').onclick=event=>{row.classList.toggle('collapsed');event.currentTarget.textContent=row.classList.contains('collapsed')?'펼치기':'접기'};
  row.querySelector('.remove').onclick=()=>{if(document.querySelectorAll('.entry').length>1){row.remove();refresh()}};
  row.querySelector('.duplicate').onclick=()=>{const value=read(row);add({...value,id:'',label:value.label?value.label+' 복사본':''})};
  row.querySelector('.select-region').onclick=()=>selectRegion(row);row.querySelector('.clear-region').onclick=()=>syncRegion(row,null);
  row.querySelector('.apply-region').onclick=()=>{const values={};['x','y','width','height'].forEach(key=>values[key]=+row.querySelector('[data-coordinate="'+key+'"]').value);if(!Object.values(values).every(Number.isFinite)||values.x<0||values.y<0||values.width<=0||values.height<=0||values.x+values.width>1.001||values.y+values.height>1.001)return error('좌표는 0~1 범위의 x, y, width, height 값으로 입력하세요.');error('');syncRegion(row,values)};
  $('entries').append(row);syncRegion(row,data.region||null);refresh();
}
function selectRegion(row){if(!row)return;if(W.busy||W.operation||S.controller)return;if(!$('imageInput').files[0])return error('영역을 지정하려면 먼저 스크린샷을 선택하세요.');error('');S.start=null;S.select=row;if(UI?.ready){UI.regionId=row.dataset.id;setCanvasMode('draw')}$('selectionText').textContent=row.querySelector('.idx').textContent+'의 영역을 드래그하세요.';$('selectionNote').classList.remove('hidden');$('previewShell').scrollIntoView({behavior:'instant',block:'center'});regions()}
function stopRegion(){S.select=null;S.start=null;S.pointerId=null;$('selectionNote').classList.add('hidden');if(UI?.ready&&UI.mode==='draw'){UI.mode='select';document.body.dataset.canvasMode='select';$('canvasDraw').setAttribute('aria-pressed','false');$('canvasSelect').setAttribute('aria-pressed','true');$('canvasHint').textContent='영역을 선택하고 모서리로 크기 조절'}regions()}
function regions(temporary){const root=$('regionLayer');root.innerHTML='';[...document.querySelectorAll('.entry')].forEach((row,index)=>{let area;try{area=row.dataset.region?JSON.parse(row.dataset.region):null}catch{}if(area&&row.dataset.hidden!=='true'){box(root,area,'region-box'+(row.dataset.locked==='true'?' locked':'')+(UX?.regionSelection?.has(row.dataset.id)?' multi-selected':'')+(row===S.select||row.dataset.id===UI?.regionId?' active':''),'항목 '+(index+1));const node=root.lastElementChild;node.dataset.regionId=row.dataset.id;if(UI?.ready&&UI.mode==='select'&&UI.tab==='settings'&&row.dataset.locked!=='true'){for(const handle of ['nw','n','ne','e','se','s','sw','w']){const grip=document.createElement('i');grip.className='region-handle';grip.dataset.handle=handle;node.append(grip)}}}});if(temporary)box(root,temporary,'region-box active','새 영역')}

function box(root,area,className,text){if(!area)return;const node=document.createElement('div');node.className=className;node.style.cssText='left:'+area.x*100+'%;top:'+area.y*100+'%;width:'+area.width*100+'%;height:'+area.height*100+'%';node.innerHTML='<span>'+esc(text)+'</span>';root.append(node)}
function point(event){const rect=$('drawLayer').getBoundingClientRect();return{x:Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width)),y:Math.max(0,Math.min(1,(event.clientY-rect.top)/rect.height))}}
$('drawLayer').onpointerdown=event=>{if(!S.select||event.button!==0||S.start)return;event.preventDefault();error('');S.pointerId=event.pointerId;S.start=point(event);$('drawLayer').setPointerCapture(event.pointerId)};
$('drawLayer').onpointermove=event=>{if(!S.start||!S.select||event.pointerId!==S.pointerId)return;const p=point(event);regions({x:Math.min(S.start.x,p.x),y:Math.min(S.start.y,p.y),width:Math.abs(p.x-S.start.x),height:Math.abs(p.y-S.start.y)})};
$('drawLayer').onpointerup=event=>{if(!S.start||!S.select||event.pointerId!==S.pointerId)return;event.preventDefault();const p=point(event),area={x:Math.min(S.start.x,p.x),y:Math.min(S.start.y,p.y),width:Math.abs(p.x-S.start.x),height:Math.abs(p.y-S.start.y)},rect=$('drawLayer').getBoundingClientRect();S.start=null;S.pointerId=null;if($('drawLayer').hasPointerCapture(event.pointerId))$('drawLayer').releasePointerCapture(event.pointerId);if(area.width*rect.width<3||area.height*rect.height<3){regions();$('selectionText').textContent='클릭한 채 가로와 세로로 조금 더 드래그하세요.';return}error('');rememberEdit();syncRegion(S.select,area);edited();stopRegion()};
$('drawLayer').onpointercancel=$('drawLayer').onlostpointercapture=()=>{S.start=null;S.pointerId=null;regions()};
$('cancelSelection').onclick=stopRegion;
function image(file){error('');if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type))return error('PNG, JPG 또는 WebP 이미지를 선택하세요.');if(file.size>10485760)return error('이미지는 10MB 이하로 올려 주세요.');resetResult();const transfer=new DataTransfer();transfer.items.add(file);$('imageInput').files=transfer.files;if(S.url)URL.revokeObjectURL(S.url);S.url=URL.createObjectURL(file);$('preview').src=S.url;$('preview').onload=()=>{if($('preview').naturalWidth*$('preview').naturalHeight>64000000)return error('이미지 해상도가 너무 큽니다.');$('previewShell').classList.remove('hidden');$('fileMeta').textContent=$('preview').naturalWidth+'×'+$('preview').naturalHeight+' · '+(file.size/1048576).toFixed(1)+'MB';$('statusFile').textContent=file.name.length>24?file.name.slice(0,21)+'…':file.name;fitViewport();step(2);regions();refreshWorkbench()}}
$('imageInput').onchange=event=>addImages(event.target.files);
$('chooseFile').onclick=event=>{event.stopPropagation();$('imageInput').removeAttribute('capture');$('imageInput').click()};
$('takePhoto').onclick=event=>{event.stopPropagation();$('imageInput').setAttribute('capture','environment');$('imageInput').click()};
['dragenter','dragover'].forEach(name=>$('dropzone').addEventListener(name,event=>{event.preventDefault();$('dropzone').classList.add('drag')}));
['dragleave','drop'].forEach(name=>$('dropzone').addEventListener(name,event=>{event.preventDefault();$('dropzone').classList.remove('drag');if(name==='drop')addImages(event.dataTransfer.files)}));
function setZoom(value,preserveMode=false){if(typeof UX!=='undefined'&&!preserveMode)UX.zoomMode='manual';S.zoom=Math.max(.02,Math.min(16,value));const width=$('preview').naturalWidth||$('canvasViewport').clientWidth;$('imageFrame').style.width=width*S.zoom+'px';$('imageFrame').style.margin='0 auto';$('zoomLabel').textContent=Math.round(S.zoom*100)+'%';$('zoomOut').disabled=S.zoom<=.02;$('zoomIn').disabled=S.zoom>=16}
$('zoomOut').onclick=()=>setZoom(S.zoom-.1);$('zoomIn').onclick=()=>setZoom(S.zoom+.1);$('fitImage').onclick=()=>{fitViewport();$('canvasViewport').scrollTo(0,0)};
$('focusCanvas').onclick=()=>{S.focus=!S.focus;document.body.classList.toggle('canvas-focus',S.focus);$('focusCanvas').textContent=S.focus?'작게 보기':'크게 보기';if(S.focus)$('previewShell').scrollIntoView({behavior:'smooth',block:'start'})};
$('addEntry').onclick=()=>{add();edited()};
$('clearEntries').onclick=()=>{$('entries').innerHTML='';S.n=0;add();edited();error('')};
$('removeDuplicates').onclick=()=>{const seen=new Set(),rows=[...document.querySelectorAll('.entry')];let removed=0;rows.forEach(row=>{const value=read(row),key=[value.language,value.mode,value.text.replace(/\r\n?/g,'\n'),JSON.stringify(value.region||null)].join('|');if(seen.has(key)&&!value.locked&&document.querySelectorAll('.entry').length>1){row.remove();removed++}else seen.add(key)});refresh();if(removed)edited();error('');if(!removed)$('removeDuplicates').textContent='중복 없음';else $('removeDuplicates').textContent=removed+'개 정리됨';setTimeout(()=>$('removeDuplicates').textContent='중복 문구 정리',1800)};

const colopts=(headers,optional)=>(optional?'<option value="">사용 안 함</option>':'')+headers.map((value,index)=>'<option value="'+index+'">'+esc(value||'(빈 헤더)')+' · '+XLSX.utils.encode_col(index)+'열</option>').join('');
function lang(value){value=String(value||'').trim().toLowerCase();return L.find(item=>item.id.toLowerCase()===value||item.label.toLowerCase()===value)}
function pregion(value){const list=String(value||'').split(',').map(Number);if(list.length!==4||!list.every(Number.isFinite))return null;const area={x:list[0],y:list[1],width:list[2],height:list[3]};return area.x>=0&&area.y>=0&&area.width>0&&area.height>0&&area.x+area.width<=1.001&&area.y+area.height<=1.001?area:null}
function xmsg(message,bad){$('excelMessage').textContent=message;$('excelMessage').style.cssText=bad?'background:#fff0f2;color:#a72d3c':''}
function invalidateExcel(){S.mapped=[];$('importExcel').disabled=true;$('excelPreview').innerHTML='';xmsg('설정이 변경되었습니다. 미리보기를 다시 확인하세요.')}
function columns(){const sheet=S.book?.Sheets[$('sheet').value];if(!sheet)return;try{S.rows=XLSX.utils.sheet_to_json(sheet,{header:1,range:$('range').value.trim()||sheet['!ref'],defval:'',raw:false})}catch{return xmsg('셀 범위를 확인하세요. 예: A1:H50',1)}const headers=(S.rows[0]||[]).map(x=>String(x).trim());['phraseColumn','idColumn','labelColumn','modeColumn','regionColumn'].forEach(id=>{$(id).innerHTML=colopts(headers,id!=='phraseColumn');$(id).disabled=!headers.length});const pick=(id,names)=>{const index=headers.findIndex(x=>names.includes(x.toLowerCase()));if(index>=0)$(id).value=String(index)};pick('phraseColumn',['문구','text','phrase','ko','en','ja','zh-cn','zh-tw']);pick('idColumn',['id','key','키']);pick('labelColumn',['화면명','화면','screen','scene']);pick('modeColumn',['검증 방식','방식','mode']);pick('regionColumn',['영역 좌표','영역','region','bbox']);$('excelLanguage').disabled=!headers.length;$('previewExcel').disabled=!headers.length;invalidateExcel();xmsg('열을 연결한 뒤 미리보기를 확인하세요.')}
$('excelFile').onchange=async event=>{try{const file=event.target.files[0];if(!file)return;if(file.size>8388608)throw Error('엑셀 파일은 8MB 이하로 선택하세요.');S.book=XLSX.read(await file.arrayBuffer(),{type:'array'});$('sheet').innerHTML=S.book.SheetNames.map(name=>'<option value="'+esc(name)+'">'+esc(name)+'</option>').join('');$('sheet').disabled=false;$('range').value=S.book.Sheets[$('sheet').value]['!ref']||'A1';$('range').disabled=false;columns()}catch(problem){xmsg(problem.message||'엑셀 파일을 읽지 못했습니다.',1)}};
$('sheet').onchange=()=>{$('range').value=S.book.Sheets[$('sheet').value]['!ref']||'A1';columns()};$('range').onchange=columns;
['phraseColumn','excelLanguage','idColumn','labelColumn','modeColumn','regionColumn'].forEach(id=>$(id).addEventListener('change',invalidateExcel));
function maprows(){const phraseIndex=+$('phraseColumn').value,header=String(S.rows[0]?.[phraseIndex]||'').trim(),language=$('excelLanguage').value==='auto'?lang(header)?.id:$('excelLanguage').value;if(!language)throw Error('문구 언어를 직접 선택하세요.');const ix=id=>$(id).value===''?-1:+$(id).value,idIndex=ix('idColumn'),labelIndex=ix('labelColumn'),modeIndex=ix('modeColumn'),regionIndex=ix('regionColumn');const all=S.rows.slice(1).map((row,index)=>{const text=String(row[phraseIndex]??''),raw=regionIndex>=0?String(row[regionIndex]??'').trim():'',area=raw?pregion(raw):null,mode=modeIndex>=0?String(row[modeIndex]??'').trim().toLowerCase():'';return{row:index+2,id:idIndex>=0?String(row[idIndex]||''):'',label:labelIndex>=0?String(row[labelIndex]||''):'',language,mode:['required','필수','all'].includes(mode)?'required':'exact',text,region:area,bad:!!raw&&!area}});return{all,items:all.filter(item=>item.text.length)}}
$('previewExcel').onclick=()=>{try{const mapped=maprows(),items=mapped.items,empty=mapped.all.length-items.length,duplicates=items.length-new Set(items.map(item=>item.text+'|'+item.language+'|'+item.mode)).size,bad=items.filter(item=>item.bad).length,long=items.filter(item=>item.text.length>3000).length;if(!items.length)throw Error('불러올 문구가 없습니다.');$('excelPreview').innerHTML='<div class="stats"><span class="chip">문구 '+items.length+'개</span><span class="chip '+(empty?'warn':'')+'">빈 셀 '+empty+'개</span><span class="chip '+(duplicates?'warn':'')+'">중복 '+duplicates+'개</span><span class="chip '+(long?'bad':'')+'">3,000자 초과 '+long+'개</span><span class="chip '+(bad?'bad':'')+'">잘못된 영역 '+bad+'개</span></div><table class="preview-table"><thead><tr><th>행</th><th>문구</th><th>언어</th><th>방식</th><th>영역</th></tr></thead><tbody>'+items.slice(0,8).map(item=>'<tr><td>'+item.row+'</td><td>'+esc(item.text)+'</td><td>'+item.language+'</td><td>'+(item.mode==='required'?'모든 글자':'그대로')+'</td><td>'+(item.bad?'오류':item.region?'지정':'전체')+'</td></tr>').join('')+'</tbody></table>';if(bad)throw Error('영역 좌표는 x,y,width,height 형식의 0~1 값으로 입력하세요.');if(long)throw Error('3,000자를 넘는 문구를 줄인 뒤 다시 확인하세요.');S.mapped=items;$('importExcel').disabled=false;xmsg('미리보기를 확인했습니다. 문구를 추가할 수 있습니다.')}catch(problem){S.mapped=[];$('importExcel').disabled=true;xmsg(problem.message,1)}};
$('importExcel').onclick=()=>{const room=80-document.querySelectorAll('.entry').length,items=S.mapped.slice(0,Math.max(0,room));items.forEach(add);edited();xmsg(items.length+'개 문구를 추가했습니다.');S.mapped=[];$('importExcel').disabled=true};

function progress(on){$('progress').classList.toggle('hidden',!on);if(on)$('progressText').textContent='OCR 서버 응답을 기다리는 중…';refreshWorkbench()}
async function requestOcr(file,targets,signal,fresh=false,provider=$('cloudProject').value,ignoreRegions=[]){const form=new FormData();form.set('ignoreRegions',JSON.stringify(ignoreRegions));form.set('image',file);form.set('entries',JSON.stringify(targets));const started=Date.now(),job=crypto.randomUUID();let stage='',polling=false;const timer=setInterval(()=>{$('progressText').textContent=(provider==='local'?'PC에서 글자를 읽는 중 · ':'AI가 글자를 읽는 중 · ')+Math.floor((Date.now()-started)/1000)+'초 경과 (최대 2분)'+(stage?' · '+stage:'');if(provider==='codex'&&!polling){polling=true;fetch('/api/progress?id='+job).then(r=>r.json()).then(p=>stage=p.stage||'').catch(()=>{}).finally(()=>polling=false)}},1000);try{const response=await fetch('/api/v1/jobs',{method:'POST',body:form,signal:AbortSignal.any([signal,AbortSignal.timeout(135000)]),headers:{'x-lingualens-job':job,'x-lingualens-provider':provider,'x-lingualens-fresh':fresh?'1':'0','x-lingualens-mode':$('analysisMode').value}}),payload=await response.json();if(response.status===401)refreshConnection();if(!response.ok)throw Error(payload.error?.message||'검증 요청을 완료하지 못했습니다.');return payload}catch(problem){if(problem.name==='TimeoutError')throw Error('분석 응답 시간이 초과되었습니다. 다시 시도하세요.');throw problem}finally{clearInterval(timer)}}
async function cropRegion(bitmap,area,enlarge=true){const x=Math.floor(area.x*bitmap.width),y=Math.floor(area.y*bitmap.height),width=Math.max(1,Math.min(bitmap.width-x,Math.ceil(area.width*bitmap.width))),height=Math.max(1,Math.min(bitmap.height-y,Math.ceil(area.height*bitmap.height))),scale=enlarge?Math.min(3,2048/Math.max(width,height)):1,canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(width*scale));canvas.height=Math.max(1,Math.round(height*scale));canvas.getContext('2d',{alpha:false}).drawImage(bitmap,x,y,width,height,0,0,canvas.width,canvas.height);paintIgnored(canvas.getContext('2d'),W.items.find(i=>i.id===W.active)?.ignoreRegions||[],bitmap.width,bitmap.height,{x,y,scale});return new Promise(resolve=>canvas.toBlob(resolve,'image/png'))}
async function analyzeImage(file,targets,signal,fresh){const ignored=W.items.find(item=>item.file===file)?.ignoreRegions||[];if(ignored.length)file=await maskedFile(file,ignored);const area=sharedRegion(targets);if(area){let bitmap;try{bitmap=await createImageBitmap(file);const blob=await cropRegion(bitmap,area,false);if(!blob)throw Error('영역 이미지를 만들지 못했습니다.');signal.throwIfAborted();const payload=await requestOcr(blob,targets.map(item=>({...item,region:null})),signal,fresh);const restored=restoreRegionResult(payload,area,{width:bitmap.width,height:bitmap.height});await autoReview(restored,bitmap,signal);return restored}finally{bitmap?.close()}}const upload=$('cloudProject').value==='local'?file:await ocrImage(file);signal.throwIfAborted();const payload=await requestOcr(upload,targets,signal,fresh,$('cloudProject').value,ignored);if($('autoReview').checked){const bitmap=await createImageBitmap(file);try{await autoReview(payload,bitmap,signal)}finally{bitmap.close()}}return payload}
async function reviewPending(file,previous,targets,signal,ids=null){
  const payload=structuredClone(previous),pending=payload.result.results.filter(item=>ids?ids.includes(item.id):!item.found);
  if(!pending.length)return payload;
  const bitmap=await createImageBitmap(file);try{if(pending.some(item=>!selectedArea(item)))return await analyzeImage(file,targets,signal,false);let readWhole=false;for(const item of pending){signal.throwIfAborted();const area=selectedArea(item);if(!area){readWhole=true;continue}await retryRegionGroup(payload,bitmap,[{...item,region:area}],signal,$('cloudProject').value)}
    if(readWhole)return await analyzeImage(file,targets,signal,false);return payload;
  }finally{bitmap.close()}
}
async function autoReview(payload,bitmap,signal){
  if(!$('autoReview').checked)return;
  const local=$('cloudProject').value==='local',provider=$('autoReviewProvider').value;
  if(provider==='off')return;
  let next=local?'local':provider;
  if(next!=='local'){const status=await(await fetch('/auth/status?provider='+next)).json();if(!status.authenticated){payload.result.autoReviewNote='AI 재확인은 로그인이 필요합니다.';return}}
  const seen=new Set();let count=0;
  for(const item of [...payload.result.results]){
    if(item.found||count>=3)continue;signal.throwIfAborted();const area=selectedArea(item);if(!area||area.width*area.height>.4)continue;
    const key=JSON.stringify(area);if(seen.has(key))continue;seen.add(key);count++;
    const scoped=payload.result.results.filter(r=>!r.found&&JSON.stringify(selectedArea(r))===key).map(r=>({...r,region:area}));
    await retryRegionGroup(payload,bitmap,scoped,signal,next);
  }
  if(local&&provider!=='local'){
    const remaining=payload.result.results.filter(r=>!r.found).slice(0,2);if(!remaining.length)return;
    const status=await(await fetch('/auth/status?provider='+provider)).json();if(!status.authenticated){payload.result.autoReviewNote='로컬 영역 재확인 완료 · AI 재확인은 로그인 후 사용할 수 있습니다.';return}
    for(const item of remaining){const area=selectedArea(item);if(area&&area.width*area.height<=.4)await retryRegionGroup(payload,bitmap,[{...item,region:area}],signal,provider)}
  }
}
function recount(payload){payload.result.reviewCount=payload.result.results.filter(item=>item.reviewRequired).length;payload.result.foundCount=payload.result.results.filter(item=>item.found).length;payload.result.found=payload.result.foundCount===payload.result.totalCount}
async function retryRegionGroup(payload,bitmap,items,signal,provider=$('cloudProject').value){const area=items[0].region,mark=(status,message)=>items.forEach(item=>{const row=payload.result.results.find(result=>result.id===item.id);if(row){row.retryStatus=status;row.retryMessage=message}});try{if(signal.aborted)throw new DOMException('Aborted','AbortError');const blob=await cropRegion(bitmap,area);if(!blob)throw Error('영역 이미지를 만들지 못했습니다.');const retry=await requestOcr(blob,items.map(item=>({...item,region:null})),signal,true,provider),mapLine=line=>({...line,boundingBox:line.boundingBox?{x:area.x+line.boundingBox.x*area.width,y:area.y+line.boundingBox.y*area.height,width:line.boundingBox.width*area.width,height:line.boundingBox.height*area.height}:null});payload.id=crypto.randomUUID();for(const found of retry.result.results){const index=payload.result.results.findIndex(result=>result.id===found.id);if(index<0)continue;payload.result.results[index]={...found,region:area,evidence:(found.evidence||[]).map(mapLine),nearestEvidence:(found.nearestEvidence||[]).map(mapLine),retryStatus:found.found?'matched':'missing',retryMessage:(provider==='local'?'로컬 OCR':provider==='codex'?'Codex':'Gemini')+' 재확인 · '+(found.found?'통과':'미통과')}}payload.result.lines.push(...(retry.result.lines||[]).map(mapLine));payload.result.extractedText=payload.result.lines.map(line=>line.text).join('\n');payload.result.regionProvider=retry.result.provider;payload.result.timing||={};payload.result.timing.regionMs=(payload.result.timing.regionMs||0)+(retry.result.timing?.totalMs||0);recount(payload)}catch(problem){if(problem.name==='AbortError')throw problem;mark('error',problem.message||'영역 재인식 중 오류가 발생했습니다.')}}
async function run(fresh=false){if(W.busy||W.operation||S.controller)return;error('');if(!S.authenticated)return error('선택한 도구의 로그인을 완료한 뒤 검증하세요.');const file=$('imageInput').files[0],targets=[...document.querySelectorAll('.entry')].map(read).filter(item=>item.text.length);if(!file)return error('검증할 스크린샷을 선택하세요.');if(!targets.length)return error('검증할 문구를 한 개 이상 입력하세요.');if(targets.some(item=>item.text.length>3000))return error('한 항목의 문구는 3,000자 이하로 입력하세요.');const currentItem=activeItem();if(currentItem)invalidateFeatureImage(currentItem,'분석 중');S.targets=targets;S.controller=new AbortController();const unlock=lockWorkspace();$('run').disabled=true;$('run').textContent='분석 중…';$('statusResult').textContent='분석 중';progress(true);try{$('progressText').textContent='이미지를 빠르게 전송하도록 준비하는 중…';const payload=await analyzeImage(file,targets,S.controller.signal,fresh===true);S.last=payload;if(currentItem)currentItem.problem='';if(S.resultUrl)URL.revokeObjectURL(S.resultUrl);S.resultUrl=URL.createObjectURL(file);await show(payload,targets,file)}catch(problem){if(currentItem)currentItem.problem=problem.name==='AbortError'?'취소됨':problem.message;dirty();queue();$('statusResult').textContent=problem.name==='AbortError'?'취소됨':'오류';error(problem.name==='AbortError'?'분석 대기를 취소했습니다.':problem.message)}finally{progress(false);$('run').disabled=false;$('run').textContent='검증 시작';S.controller=null;unlock();refreshWorkbench()}}
$('run').onclick=()=>run();$('retry').onclick=()=>run(true);$('cancelRun').onclick=()=>S.controller?.abort();
async function saveHistory(payload,file){try{const data=payload.result,image=await historyImage(file);await historyPut({id:payload.id,at:new Date().toISOString(),foundCount:data.foundCount,totalCount:data.totalCount,provider:data.provider,image,targets:S.targets.map(item=>({id:item.id,label:item.label,text:item.text,language:item.language,mode:item.mode,region:item.region})),results:data.results.map(item=>({id:item.id,label:item.label,text:item.text,found:item.found,reason:item.reason,observedText:item.observedText}))});const history=await historyAll();await historyDelete(history.slice(HISTORY_LIMIT).map(item=>item.id));await renderHistory()}catch(problem){console.warn('최근 기록을 저장하지 못했습니다.',problem)}}
async function show(payload,targets,file,persist=true){const data=payload.result,found=data.results.filter(item=>item.found).length,elapsed=data.timing?.cacheHit?'저장된 OCR 재사용 · ':data.timing?.providerMs?('OCR '+(data.timing.providerMs/1000).toFixed(1)+'초 · '):'';$('resultCard').classList.remove('hidden');$('resultProvider').textContent=(data.analysisScope==='region'?'지정 영역 · ':data.lines.some(line=>line.boundingBox)?'좌표 포함 · ':'글자만 확인 · ')+(data.provider==='local-rapidocr'?'로컬 OCR':data.provider)+(data.regionProvider?' · 영역 재확인 '+(data.regionProvider==='local-rapidocr'?'로컬 OCR':data.regionProvider):'');$('summary').className='summary '+(found===targets.length?'pass':'fail');$('summary').innerHTML='<div><strong>'+(found===targets.length?'✓ 모든 문구가 일치합니다.':'확인이 필요한 문구가 있습니다.')+'</strong><span>'+found+' / '+targets.length+'개 통과</span></div><span>'+elapsed+(data.reviewCount?('확인 필요 '+data.reviewCount+'개 · '):'')+(data.timing?.regionMs?'영역 재확인 '+(data.timing.regionMs/1000).toFixed(1)+'초 · ':'')+'추정 신뢰도 '+Math.round((data.confidence||0)*100)+'%'+(data.autoReviewNote?' · '+esc(data.autoReviewNote):'')+'</span>';$('statusResult').textContent=found+'/'+targets.length+' 통과';$('ocrText').textContent=orderedOcrLines(data.lines,$('ocrLayout')?.value||'raw').map(l=>l.text).join('\n')||data.extractedText||'인식된 텍스트가 없습니다.';$('resultImage').src=S.resultUrl;if(UX.viewImage!==W.active){UX.viewImage=W.active;UX.filter='all';UX.search='';if($('resultSearch'))$('resultSearch').value=''}render(UX.filter);step(3);setWorkbenchTab('results');refreshWorkbench();if(persist){snapshot();dirty();queue();await saveHistory(payload,file)}}
const visibleSpace=value=>esc(value).replace(/ /g,'<span class="visible-space" aria-label="공백">·</span>').replace(/\t/g,'<span class="visible-space" aria-label="탭">⇥</span>').replace(/\n/g,'<span class="visible-space" aria-label="줄바꿈">↵<br></span>');
function diffHtml(expected,observed){if(!observed)return '';const html=unicodeChanges(expected,observed).map(p=>p.type==='same'?visibleSpace(p.text):'<'+(p.type==='added'?'ins':'del')+'>'+visibleSpace(p.text)+'</'+(p.type==='added'?'ins':'del')+'>').join('');return '<div class="diff"><span>기대 문구 ↔ OCR · 공백 · / 줄바꿈 ↵</span><code>'+html+'</code></div>'}
function render(filter){UX.filter=filter;const pane=$('resultsPane'),scroll=pane?.scrollTop||0;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));const items=visibleResults(filter);if($('reviewFilter'))$('reviewFilter').value=filter;if($('reviewListCount'))$('reviewListCount').textContent=items.length+' / '+(S.last?.result?.results?.length||0)+'개 문구';$('results').innerHTML=items.map(item=>{const m=manualState(activeItem(),item.id),stale=activeItem()?.reviews?.[item.id]&&!m;return '<button class="result-item" data-id="'+esc(item.id)+'"><span class="result-name">'+esc(item.label||item.text.split(/\r?\n/)[0])+'<small>'+esc(L.find(l=>l.id===item.language)?.label||item.language)+' · '+Math.round((item.confidence||0)*100)+'%</small></span><span class="result-verdicts"><span class="verdict '+(item.found?'good':item.reviewRequired?'warn':'bad')+'">자동 '+(item.found?'✓ 통과':item.reviewRequired?'확인 필요':'미통과')+'</span><span class="verdict '+(m?.verdict==='issue'?'bad':m?.verdict==='accepted'?'good':'neutral')+'">'+(stale?'재검수':m?.verdict==='issue'?'수동 문제':m?.verdict==='accepted'?'확인 완료':'미검수')+'</span></span></button>'}).join('')||'<p>해당 결과가 없습니다.</p>';$('results').querySelectorAll('.result-item').forEach(button=>button.onclick=()=>{$('results').querySelectorAll('.result-item').forEach(item=>item.classList.remove('selected'));button.classList.add('selected');$('results').querySelectorAll('.result-item').forEach(el=>el.setAttribute('aria-pressed',String(el===button)));evidence(button.dataset.id,true)});const selected=items.find(item=>item.id===S.selectedResult)||items[0];$('results').querySelectorAll('.result-item').forEach(button=>{const active=button.dataset.id===selected?.id;button.classList.toggle('selected',active);button.setAttribute('aria-pressed',String(active))});evidence(selected?.id);if(pane)pane.scrollTop=scroll}
function evidence(id,focus=false){S.selectedResult=id;const root=$('resultBoxes');root.innerHTML='';const item=S.last?.result?.results?.find(result=>result.id===id);$('retryRegion').classList.toggle('hidden',!item?.region||item.found);$('verifyRegionAi').disabled=!selectedArea(item); workbenchEvidence(item,focus);refreshFeatureResults();if(!item)return;const lines=item.evidence?.length?item.evidence:item.nearestEvidence?.length?item.nearestEvidence:(item.region?[{text:'지정 영역',boundingBox:item.region}]:[]),className=item.evidence?.length?(item.reviewRequired?'review-box':'evidence-box'):item.nearestEvidence?.length?'nearest-box':'region-box active';lines.forEach(line=>box(root,line.boundingBox,className,line.text||'지정 영역'))}
$('retryRegion').onclick=async()=>{const item=S.last?.result?.results?.find(result=>result.id===S.selectedResult),file=$('imageInput').files[0];if(!item?.region||!file||S.controller||W.busy||W.operation)return;const unlock=lockWorkspace();S.controller=new AbortController();$('retryRegion').disabled=true;progress(true);$('progressText').textContent='선택 영역을 확대해 다시 읽는 중…';let bitmap;try{bitmap=await createImageBitmap(file);await retryRegionGroup(S.last,bitmap,[item],S.controller.signal);await show(S.last,S.targets,file)}catch(problem){error(problem.name==='AbortError'?'영역 재인식을 취소했습니다.':problem.message)}finally{bitmap?.close();S.controller=null;$('retryRegion').disabled=false;progress(false);unlock()}};
document.querySelectorAll('.filter').forEach(button=>button.onclick=()=>{document.querySelectorAll('.filter').forEach(item=>item.classList.remove('active'));button.classList.add('active');render(button.dataset.filter)});
function download(name,data,type){const url=URL.createObjectURL(new Blob([data],{type})),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportRows(){return[['ID','화면명','언어','방식','입력 문구','결과','실패 원인','일치 문구','가까운 OCR 문구','신뢰도'],...S.last.result.results.map(item=>[item.id,item.label,item.language,item.mode,item.text,item.found?'통과':item.reviewRequired?'확인 필요':'미통과',item.reason,item.matchedText,item.observedText,Math.round((item.confidence||0)*100)])]}
$('exportJson').onclick=()=>S.last&&download('lingualens-'+S.last.id+'.json',JSON.stringify(S.last,null,2),'application/json');
$('exportCsv').onclick=()=>{if(!S.last)return;const quote=value=>'"'+String(value??'').replace(/"/g,'""')+'"';download('lingualens-'+S.last.id+'.csv','\ufeff'+exportRows().map(row=>row.map(quote).join(',')).join('\r\n'),'text/csv;charset=utf-8')};
$('exportXlsx').onclick=()=>{if(!S.last)return;const sheet=XLSX.utils.aoa_to_sheet(exportRows());sheet['!cols']=[{wch:18},{wch:22},{wch:10},{wch:12},{wch:42},{wch:10},{wch:24},{wch:36},{wch:36},{wch:10}];const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'검증 결과');XLSX.writeFile(book,'lingualens-'+S.last.id+'.xlsx')};
async function migrateLegacyHistory(){try{const legacy=JSON.parse(localStorage.getItem('lingualens-history')||'[]');for(const item of legacy)await historyPut({...item,image:null});localStorage.removeItem('lingualens-history')}catch{}}
async function renderHistory(){S.historyUrls.forEach(url=>URL.revokeObjectURL(url));S.historyUrls=[];try{const history=(await historyAll()).slice(0,HISTORY_LIMIT);$('history').innerHTML=history.length?history.map(item=>{const imageUrl=item.image?URL.createObjectURL(item.image):'';if(imageUrl)S.historyUrls.push(imageUrl);const image=imageUrl?'<img class="history-thumb" src="'+imageUrl+'" alt="'+esc(new Date(item.at).toLocaleString('ko-KR'))+' 검증 이미지">':'<div class="history-thumb empty">이미지 없음</div>';const preview=imageUrl?'<img class="history-preview" src="'+imageUrl+'" alt="검증 당시 이미지">':'';return'<details class="history-item"><summary><div class="history-main">'+image+'<span><strong>'+new Date(item.at).toLocaleString('ko-KR')+'</strong><small>'+esc(item.provider||'OCR')+'</small></span></div><b class="'+(item.foundCount===item.totalCount?'ok':'no')+'">'+item.foundCount+' / '+item.totalCount+' 통과</b></summary><div class="history-detail">'+preview+'<div><button class="secondary small restore-history" type="button" data-id="'+esc(item.id)+'"'+(item.targets?.length?'':' disabled')+'>이 설정 다시 사용</button><p class="help">검증하려면 원본 스크린샷을 다시 선택하세요.</p><ul>'+(item.results||[]).map(result=>'<li><span>'+(result.found?'✓':'!')+' '+esc(result.label||result.text)+'</span><small>'+esc(result.reason)+(result.observedText?' · OCR: '+esc(result.observedText):'')+'</small></li>').join('')+'</ul></div></div></details>'}).join(''):'<p class="empty-history">아직 저장된 검증 기록이 없습니다.</p>';$('history').querySelectorAll('.restore-history').forEach(button=>button.onclick=async()=>{if(W.busy||W.operation||S.controller)return;const record=history.find(item=>item.id===button.dataset.id);if(!record?.targets?.length)return;resetResult();$('entries').replaceChildren();record.targets.slice(0,80).forEach(add);dirty();$('entries').scrollIntoView({behavior:'smooth',block:'start'});error($('imageInput').files[0]?'': '원본 스크린샷을 선택하면 복원한 설정으로 검증할 수 있습니다.')})}catch(problem){$('history').innerHTML='<p class="empty-history">최근 기록을 불러오지 못했습니다. 브라우저 저장 공간을 확인하세요.</p>';console.warn('최근 기록을 불러오지 못했습니다.',problem)}}
$('clearHistory').onclick=async()=>{await historyClear().catch(()=>{});localStorage.removeItem('lingualens-history');await renderHistory()};
document.addEventListener('keydown',event=>{if(document.querySelector('dialog[open]'))return;if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();if(!$('run').disabled)runPrimary();return}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='n'){event.preventDefault();if(W.busy||W.operation||S.controller)return;add();edited();document.querySelector('.entry:last-child .phrase')?.focus();return}if(event.key==='Escape'){if(S.select)stopRegion();else if(S.focus)$('focusCanvas').click();else if(S.controller)S.controller.abort()}});
async function refreshConnection(){try{const provider=$('cloudProject').value;const response=await fetch('/auth/status?provider='+provider,{cache:'no-store'}),status=await response.json();if(provider!==$('cloudProject').value)return;S.connected=!!status.connected;S.authenticated=!!status.authenticated;$('connectGoogle').classList.toggle('hidden',provider==='local');$('connectState').textContent=provider==='local'?(status.configured?'로컬 OCR 준비됨':'로컬 OCR 파일 확인 필요'):!status.configured?'CLI 설치 필요':status.authenticated?'로그인됨':'로그인 필요';$('connectGoogle').disabled=!!status.authenticated;$('connectGoogle').textContent=!status.configured?'설치 방법 보기':status.authenticated?'로그인 완료':'웹페이지에서 로그인';$('disconnectGoogle').classList.add('hidden');document.querySelector('.connect-card').classList.toggle('connected',!!status.authenticated);$('connectHelp').textContent=provider==='local'?'이미지를 PC 안에서 분석합니다. 한국어·영문·일문·중국어 등을 지원하며, 작은 글자나 장식 글자는 AI 재확인으로 확인하세요. OCR 원문은 이 PC에 7일간 재사용용으로 저장됩니다.':status.authenticated?'로그인이 확인되었습니다. 검증을 시작할 수 있습니다.':status.configured?'버튼을 누르면 공식 로그인 웹페이지가 열립니다. 웹페이지에서 로그인하세요.':provider==='gemini'?'Antigravity CLI가 아직 없습니다. 설치 방법 보기에서 안내를 열고 설치한 다음 설치 상태를 다시 확인하세요.':'Codex CLI를 찾지 못했습니다. 설치 방법을 확인한 뒤 설치 상태를 다시 확인하세요.'}catch{S.authenticated=false;$('connectState').textContent='연결 상태 확인 실패';$('connectGoogle').disabled=false}}
$('cloudProject').onchange=()=>{S.authenticated=false;refreshConnection()};
const installUrl=provider=>provider==='gemini'?'https://www.antigravity.google/docs/cli/install/':'https://developers.openai.com/codex/cli';
$('connectGoogle').onclick=async()=>{const provider=$('cloudProject').value;if(provider==='local')return;if(!S.connected){window.open(installUrl(provider),'_blank','noopener');error(provider==='gemini'?'Antigravity CLI를 설치한 뒤 설치 상태를 다시 확인하세요.':'Codex CLI를 설치한 뒤 설치 상태를 다시 확인하세요.');return}try{$('connectGoogle').disabled=true;$('connectState').textContent='로그인 페이지 여는 중';const response=await fetch('/auth/login?provider='+provider,{method:'POST'}),payload=await response.json();if(!response.ok)throw Error(payload.error?.message||'로그인 페이지를 열지 못했습니다.');$('connectState').textContent='브라우저에서 로그인 중';$('connectHelp').textContent=payload.message||'공식 로그인 웹페이지에서 계정 로그인을 마치면 이 화면에 결과가 표시됩니다.';let attempts=0;const timer=setInterval(async()=>{try{const result=await(await fetch('/auth/session?id='+encodeURIComponent(payload.id),{cache:'no-store'})).json();if(result.state==='waiting'&&++attempts<150)return;clearInterval(timer);if(result.state==='complete'){error('');await refreshConnection()}else{error(result.message||'로그인을 완료하지 못했습니다.');await refreshConnection()}}catch{clearInterval(timer);await refreshConnection()}},2000)}catch(problem){error(problem.message);await refreshConnection()}};
$('refreshCli').onclick=refreshConnection;
async function refreshVersion(online=false){try{const button=$('versionCheck');button.textContent='버전 확인 중…';const response=await fetch('/app/version'+(online?'?latest=1':''),{cache:'no-store'}),data=await response.json();button.textContent=online?(data.latest?(data.upToDate?'v'+data.current+' · 최신':'v'+data.current+' → v'+data.latest):'v'+data.current+' · 최신 확인 실패'):'v'+data.current+' · 최신 확인';button.title=online&&data.latest?'현재 '+data.current+' · 최신 '+data.latest:'현재 버전 '+data.current+' · 눌러서 최신 버전 확인'}catch{$('versionCheck').textContent='버전 확인 실패'}}
$('versionCheck').onclick=()=>refreshVersion(true);
$('disconnectGoogle').onclick=()=>{};
setInterval(()=>fetch('/healthz').catch(()=>{}),30000);
if(new URLSearchParams(location.search).has('connected'))history.replaceState(null,'',location.pathname);

function selectedArea(item){
  if(item?.region)return item.region;
  const boxes=(item?.evidence?.length?item.evidence:item?.nearestEvidence||[]).map(line=>line.boundingBox).filter(Boolean);
  if(!boxes.length)return null;
  const x=Math.max(0,Math.min(...boxes.map(b=>b.x))-.01),y=Math.max(0,Math.min(...boxes.map(b=>b.y))-.01);
  return{x,y,width:Math.min(1,Math.max(...boxes.map(b=>b.x+b.width))+.01)-x,height:Math.min(1,Math.max(...boxes.map(b=>b.y+b.height))+.01)-y};
}
$('verifyRegionAi').onclick=async()=>{
  const item=S.last?.result?.results?.find(x=>x.id===S.selectedResult),area=selectedArea(item),file=$('imageInput').files[0],provider=$('regionProvider').value;
  if(W.busy||W.operation||S.controller)return;
  if(!area||!file)return error('결과 항목을 선택하세요. 영역이 없으면 문구의 검증 영역을 먼저 지정하세요.');
  if(provider!=='local'){
    const status=await(await fetch('/auth/status?provider='+provider)).json();
    if(!status.authenticated){$('cloudProject').value=provider;await refreshConnection();return error('선택한 AI 도구에 로그인한 뒤 영역 재확인을 다시 누르세요.')}
    if(W.busy||W.operation||S.controller)return;
  }
  const unlock=lockWorkspace();S.controller=new AbortController();progress(true);let bitmap;
  try{bitmap=await createImageBitmap(file);await retryRegionGroup(S.last,bitmap,[{...item,region:area}],S.controller.signal,provider);await show(S.last,S.targets,file)}
  catch(e){error(e.name==='AbortError'?'영역 재확인을 취소했습니다.':e.message)}finally{bitmap?.close();S.controller=null;progress(false);unlock()}
};
$('clearOcrCache').onclick=async()=>{if(W.busy||W.operation||S.controller)return;try{const response=await fetch('/api/ocr-cache/clear',{method:'POST'});if(!response.ok)throw Error('OCR 캐시를 비우지 못했습니다.');$('workspaceStatus').textContent='OCR 캐시를 비웠습니다. 다음 검증에서 이미지를 새로 읽습니다.'}catch(e){error(e.message)}};

${workspaceClient}
${workspaceUpgrade}
${workbenchClient}
${featureClient}
${uxClient}
${enhancementClient}
mountWorkbench();mountFeatures();mountUx();mountEnhancements();
add();refreshLibrary();refreshConnection();refreshVersion();migrateLegacyHistory().then(renderHistory);setInterval(()=>fetch('/healthz').catch(()=>{}),15000);})();`;

