export const enhancementClient=String.raw`
function saveNote(item,id,value){reviewNote(item,id,value);dirty();}
function visibleResults(filter=UX.filter){const item=activeItem();let rows=(S.last?.result?.results||[]).filter(r=>resultMatches(r,item,filter,UX.search||''));if(UX.sort==='confidence')rows.sort((a,b)=>(a.confidence??0)-(b.confidence??0));return rows}
function analysisDetails(data){const timing=data.timing||{};return [timing.cacheHit?'저장된 OCR 재사용':timing.providerMs!=null?'OCR '+(timing.providerMs/1000).toFixed(1)+'초':'',timing.regionMs?'영역 재확인 '+(timing.regionMs/1000).toFixed(1)+'초':'',data.autoReviewNote||''].filter(Boolean).join(' · ')}
function showPreferences(value){UX.preferences=normalizePreferences(value);const p=UX.preferences,shell=document.querySelector('.workbench-shell');shell.style.setProperty('--left-width',p.leftWidth+'px');shell.style.setProperty('--right-width',p.rightWidth+'px');document.body.style.setProperty('--review-font',p.fontSize+'px');document.body.dataset.density=p.density;document.body.dataset.minimap=p.minimap?'show':'hide';setLayoutMode(p.layout);$('uiFont').value=p.fontSize;$('uiDensity').value=p.density;$('uiMinimap').checked=p.minimap;}
function persistPreferences(immediate=false){if(!UX.preferencesReady)return;const shell=document.querySelector('.workbench-shell');UX.preferences=normalizePreferences({...UX.preferences,layout:document.body.dataset.layout,leftWidth:parseInt(shell.style.getPropertyValue('--left-width')),rightWidth:parseInt(shell.style.getPropertyValue('--right-width')),fontSize:Number($('uiFont').value),density:$('uiDensity').value,minimap:$('uiMinimap').checked});clearTimeout(UX.preferenceTimer);UX.preferenceTimer=setTimeout(async()=>{try{await projectRequest('/api/workspace/preferences',UX.preferences);$('preferenceStatus').textContent='화면 설정 저장됨'}catch(e){$('preferenceStatus').textContent='화면 설정 저장 실패 · '+e.message}},immediate===true?0:500)}
function captureImageView(){const item=activeItem(),v=$('canvasViewport'),f=$('imageFrame');if(!UX.enhanced||UX.restoringView||!item||!$('preview').naturalWidth||!f.clientWidth)return;item.view={zoom:S.zoom,mode:UX.zoomMode,x:Math.max(0,Math.min(1,(v.scrollLeft+v.clientWidth/2)/f.clientWidth)),y:Math.max(0,Math.min(1,(v.scrollTop+v.clientHeight/2)/f.clientHeight))}}
function restoreImageView(){if(!UX.enhanced)return;const item=activeItem(),view=item?.view;UX.restoringView=true;requestAnimationFrame(()=>{if(view){UX.zoomMode=view.mode;setZoom(view.mode==='fit'?fitScale($('preview').naturalWidth,$('preview').naturalHeight,$('canvasViewport').clientWidth,$('canvasViewport').clientHeight):view.zoom,true);requestAnimationFrame(()=>{const v=$('canvasViewport'),f=$('imageFrame');v.scrollLeft=view.x*f.clientWidth-v.clientWidth/2;v.scrollTop=view.y*f.clientHeight-v.clientHeight/2;UX.restoringView=false;updateMinimap()})}else{fitViewport();UX.restoringView=false;updateMinimap()}})}
function updateMinimap(){if(!UX.enhanced)return;const p=$('preview'),map=$('imageMinimap'),img=$('minimapImage'),rect=$('minimapView'),v=$('canvasViewport'),f=$('imageFrame');map.hidden=!p.naturalWidth;if(!p.naturalWidth)return;if(img.src!==p.src)img.src=p.src;rect.style.left=Math.min(100,v.scrollLeft/f.clientWidth*100)+'%';rect.style.top=Math.min(100,v.scrollTop/f.clientHeight*100)+'%';rect.style.width=Math.min(100,v.clientWidth/f.clientWidth*100)+'%';rect.style.height=Math.min(100,v.clientHeight/f.clientHeight*100)+'%'}
function selectedRegionRows(){return [...$('entries').children].filter(r=>UX.regionSelection.has(r.dataset.id))}
function updateRegionTools(){if(!UX.enhanced)return;const rows=[...$('entries').children];for(const row of rows){let tools=row.querySelector('.region-row-tools');if(!tools){tools=document.createElement('div');tools.className='region-row-tools';tools.innerHTML='<label><input type="checkbox" class="region-select">선택</label><button type="button" class="ghost small region-lock">잠금</button><button type="button" class="ghost small region-hide">숨김</button>';row.append(tools);tools.querySelector('.region-select').onchange=e=>{if(e.target.checked)UX.regionSelection.add(row.dataset.id);else UX.regionSelection.delete(row.dataset.id);regions();updateRegionTools()};tools.querySelector('.region-lock').onclick=()=>{if(featureBusy())return;rememberEdit();row.dataset.locked=row.dataset.locked==='true'?'false':'true';snapshot();dirty();regions();updateRegionTools()};tools.querySelector('.region-hide').onclick=()=>{if(featureBusy())return;rememberEdit();row.dataset.hidden=row.dataset.hidden==='true'?'false':'true';snapshot();dirty();regions();updateRegionTools()}}
 tools.querySelector('input').checked=UX.regionSelection.has(row.dataset.id);tools.querySelector('.region-lock').textContent=row.dataset.locked==='true'?'잠금 해제':'잠금';tools.querySelector('.region-lock').setAttribute('aria-pressed',String(row.dataset.locked==='true'));tools.querySelector('.region-hide').textContent=row.dataset.hidden==='true'?'표시':'숨김';tools.querySelector('.region-hide').setAttribute('aria-pressed',String(row.dataset.hidden==='true'));for(const b of tools.querySelectorAll('button,input'))b.disabled=featureBusy();for(const b of row.querySelectorAll('.clear-region,.apply-region,.select-region,.remove'))b.disabled=featureBusy()||row.dataset.locked==='true'}
 $('clearEntries').disabled=featureBusy()||rows.some(r=>r.dataset.locked==='true');$('regionSelectedCount').textContent=selectedRegionRows().length+'개 선택';for(const id of ['regionsLock','regionsHide','regionsDelete','regionsShift'])$(id).disabled=featureBusy()||!selectedRegionRows().length;}
function regionBatch(kind){if(featureBusy())return;const rows=selectedRegionRows();if(!rows.length)return;const moves=new Map();if(kind==='shift'){const p=$('preview'),dx=Number($('regionsDx').value)/p.naturalWidth,dy=Number($('regionsDy').value)/p.naturalHeight;if(!Number.isFinite(dx)||!Number.isFinite(dy))return;const movable=rows.filter(r=>r.dataset.locked!=='true'&&r.dataset.region),areas=moveRegionGroup(movable.map(r=>JSON.parse(r.dataset.region)),dx,dy);movable.forEach((r,i)=>moves.set(r,areas[i]))}rememberEdit();let affects=false;
 for(const row of rows){if(kind==='lock')row.dataset.locked='true';else if(kind==='unlock')row.dataset.locked='false';else if(kind==='hide')row.dataset.hidden=row.dataset.hidden==='true'?'false':'true';else if(row.dataset.locked!=='true'){if(kind==='delete'){row.remove();UX.regionSelection.delete(row.dataset.id);affects=true}else if(kind==='shift'&&row.dataset.region){syncRegion(row,moves.get(row));affects=true}}}
 if(affects)edited();else{snapshot();dirty()}regions();updateRegionTools();}
function diffInWorker(before,after,width,height,threshold,signal){return new Promise((resolve,reject)=>{const worker=new Worker('/comparison-worker.js',{type:'module'});const finish=(error,value)=>{signal.removeEventListener('abort',abort);worker.terminate();error?reject(error):resolve(value)},abort=()=>finish(new DOMException('취소됨','AbortError'));if(signal.aborted){abort();return}signal.addEventListener('abort',abort,{once:true});worker.onerror=e=>finish(Error(e.message||'화면 비교 작업 오류'));worker.onmessage=e=>{if(e.data.stage){$('diffInfo').textContent=e.data.stage;return}finish(e.data.error?Error(e.data.error):null,e.data)};worker.postMessage({before:before.buffer,after:after.buffer,width,height,threshold},[before.buffer,after.buffer])})}
function comparisonPresentation(){const mode=$('compareDisplay').value,blend=$('compareBlend').value/100;clearInterval(F.blinkTimer);F.blinkTimer=null;document.querySelector('.compare-images').dataset.presentation=mode;const c=$('diffCanvas'),ctx=c.getContext('2d');if(!F.compareOriginals?.diff)return;
 if(mode==='slider'){ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(F.compareOriginals.after,0,0);ctx.save();ctx.beginPath();ctx.rect(0,0,c.width*blend,c.height);ctx.clip();ctx.drawImage(F.compareOriginals.before,0,0);ctx.restore()}
 else if(mode==='blink'){let baseline=false;const draw=()=>{baseline=!baseline;ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(baseline?F.compareOriginals.before:F.compareOriginals.after,0,0);$('compareFrameLabel').textContent=baseline?'기준 이미지':'현재 이미지'};draw();F.blinkTimer=setInterval(draw,600)}
 else{ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(F.compareOriginals.diff,0,0);$('compareFrameLabel').textContent='차이 강조'}
}
function refreshChangedRegions(){const data=activeItem()?.comparison,regions=data?.regions||[];$('changedRegionList').innerHTML=regions.map((r,i)=>'<button class="ghost small" data-change="'+i+'">'+(i+1)+'. '+r.count.toLocaleString()+'픽셀 · '+r.x+', '+r.y+'</button>').join('')||'<p class="help">표시할 변경 위치가 없습니다.</p>';$('changedRegionList').querySelectorAll('button').forEach(b=>b.onclick=()=>focusChange(Number(b.dataset.change)));$('changeCount').textContent=regions.length+'곳'+(data?.totalRegions>regions.length?' / 전체 '+data.totalRegions+'곳':'');$('nextChange').disabled=!regions.length;UX.changeIndex=-1;}
function focusChange(index){const region=activeItem()?.comparison?.regions?.[index];if(!region)return;UX.changeIndex=index;const canvas=$('diffCanvas'),v=canvas.parentElement;compareView(Math.min(8,Math.max(.2,Math.min(v.clientWidth/(region.width+60),v.clientHeight/(region.height+60)))));for(const box of document.querySelectorAll('.comparison-viewport')){box.scrollLeft=(region.x+region.width/2)*UX.compareZoom-box.clientWidth/2;box.scrollTop=(region.y+region.height/2)*UX.compareZoom-box.clientHeight/2}$('changeCount').textContent=(index+1)+' / '+activeItem().comparison.regions.length+'곳';}
function cloneCanvas(source){const c=document.createElement('canvas');c.width=source.width;c.height=source.height;c.getContext('2d').drawImage(source,0,0);return c}
function baselineRecord(item,baseline){return {...structuredClone(baseline),id:crypto.randomUUID(),at:new Date().toISOString(),tag:$('baselineTag').value.slice(0,80),language:item.targets[0]?.language||'',width:baseline.width||0,height:baseline.height||0}}
function rememberBaseline(item,baseline){item.baselineHistory||=[];const record=baselineRecord(item,baseline);item.baselineHistory.unshift(record);item.baselineHistory=item.baselineHistory.slice(0,10);item.baseline=structuredClone(record);return record}
function refreshBaselineHistory(){const item=activeItem();if(!item)return;$('baselineHistory').innerHTML=(item.baselineHistory||[]).map(b=>'<div class="baseline-history-row"><span>'+esc(b.tag||b.name)+'<small>'+esc(b.language)+' · '+(b.width&&b.height?b.width+'×'+b.height+' · ':'')+esc(new Date(b.at).toLocaleString('ko-KR'))+'</small></span><button class="ghost small" data-baseline="'+b.id+'">이 기준 사용</button></div>').join('')||'<p class="help">기준 이미지를 지정하면 최대 10개의 이력을 보관합니다.</p>';$('baselineHistory').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(featureBusy())return;const record=item.baselineHistory.find(r=>r.id===b.dataset.baseline);item.baseline=structuredClone(record);item.comparison=null;resetComparisonView();dirty();$('baselineInfo').textContent='기준 복원: '+(record.tag||record.name)});}
async function baselineFromCurrent(){if(featureBusy()||!activeItem())return;const item=activeItem(),unlock=lockWorkspace();try{const size=await imageSize(item),ref=item.imageRef||await imageReference(item.file);item.imageRef=ref;rememberBaseline(item,{image:ref,name:item.file.name,width:size.width,height:size.height,x:0,y:0,scale:false});item.comparison=null;resetComparisonView();dirty();refreshBaselineHistory();$('baselineInfo').textContent='현재 이미지를 기준으로 보관했습니다.'}catch(e){$('baselineInfo').textContent=e.message}finally{unlock()}}
function profileOptions(){return normalizeProfile({provider:$('cloudProject').value,mode:$('analysisMode').value,autoReview:$('autoReviewProvider').value,ocrLayout:$('ocrLayout').value})}
function applyProfileOptions(profile){const p=normalizeProfile(profile);$('cloudProject').value=p.provider;$('analysisMode').value=p.mode;$('autoReviewProvider').value=p.autoReview;$('autoReview').checked=p.autoReview!=='off';$('ocrLayout').value=p.ocrLayout;refreshConnection();}
async function openBaselinePairing(files){if(featureBusy())return;const list=[...files];if(!list.length)return;const matches=W.items.map(item=>{const key=item.file.name.replace(/\.[^.]+$/,'').toLocaleLowerCase(),found=list.filter(f=>f.name.replace(/\.[^.]+$/,'').toLocaleLowerCase()===key);return {item,file:found.length===1?found[0]:null,count:found.length}});F.baselinePairing=matches;$('baselinePairPreview').innerHTML=matches.map(p=>'<p>'+esc(p.item.file.name)+' → '+(p.file?esc(p.file.name):p.count>1?'이름 중복 · 적용 제외':'일치 파일 없음')+'</p>').join('');$('applyBaselinePairs').disabled=!matches.some(p=>p.file);$('baselinePairDialog').showModal();}
async function applyBaselinePairs(){if(featureBusy()||!F.baselinePairing)return;const unlock=lockWorkspace();let completed=0;try{const plan=[];for(const p of F.baselinePairing.filter(p=>p.file)){if(p.file.size>10485760||!['image/png','image/jpeg','image/webp'].includes(p.file.type))throw Error('기준 이미지는 PNG·JPG·WebP 10MB 이하로 선택하세요.');const bitmap=await createImageBitmap(p.file);if(bitmap.width*bitmap.height>64000000){bitmap.close();throw Error('기준 이미지 해상도가 너무 큽니다.')}const size={width:bitmap.width,height:bitmap.height};bitmap.close();plan.push({...p,size,image:await imageReference(p.file)})}for(const p of plan){rememberBaseline(p.item,{image:p.image,name:p.file.name,...p.size,x:0,y:0,scale:false});p.item.comparison=null;completed++}resetComparisonView();dirty();refreshBaselineHistory();$('baselinePairDialog').close();$('baselineInfo').textContent=completed+'장에 기준 이미지 연결 완료'}catch(e){$('baselinePairError').textContent=e.message}finally{unlock()}}
function reviewKeyboard(event){if(!UX.enhanced||event.repeat||featureBusy()||document.querySelector('dialog[open]')||event.target.closest('input,textarea,select,[contenteditable=true]')||event.ctrlKey||event.metaKey||event.altKey)return;const key=event.key.toLowerCase();
 if(key===' '){event.preventDefault();if(!UX.previousMode){UX.previousMode=UI.mode;setCanvasMode('move')}return}
 if(UI.tab!=='results'||!S.last)return;if(key==='a'){event.preventDefault();saveManualReview('accepted')}else if(key==='i'){event.preventDefault();saveManualReview('issue')}else if(key==='n'){event.preventDefault();nextReviewTarget(true)}else if(key==='p'){event.preventDefault();const rows=visibleResults(),index=rows.findIndex(r=>r.id===S.selectedResult);if(rows.length)selectReviewTarget(rows[(index-1+rows.length)%rows.length].id)}
}
function mountEnhancements(){
 UX.regionSelection=new Set();UX.search='';UX.sort='original';UX.preferences=normalizePreferences();UX.enhanced=true;
 const overview=document.createElement('div');overview.className='review-overview';overview.append($('summary'));document.querySelector('.workbench-tabs').after(overview);
 const toolbar=document.createElement('div');toolbar.className='review-filters';toolbar.innerHTML='<input id="resultSearch" placeholder="문구·OCR·메모 검색" aria-label="검수 문구 검색"><div><select id="reviewFilter" aria-label="검수 상태"><option value="all">모든 문구</option><option value="unresolved">미해결</option><option value="unreviewed">미검수</option><option value="issue">수동 문제 있음</option><option value="stale">재검수 필요</option><option value="accepted">확인 완료</option><option value="pass">자동 통과</option><option value="review">자동 확인 필요</option><option value="fail">자동 미통과</option></select><select id="resultSort" aria-label="문구 정렬"><option value="original">설정 순서</option><option value="confidence">인식 점수 낮은 순</option></select></div><p id="reviewListCount" class="help"></p>';toolbar.append(document.querySelector('.result-more'));$('results').before(toolbar);document.querySelector('.filter-group').remove();$('resultSearch').oninput=()=>{UX.search=$('resultSearch').value;render(UX.filter)};$('reviewFilter').onchange=()=>render($('reviewFilter').value);$('resultSort').onchange=()=>{UX.sort=$('resultSort').value;render(UX.filter)};
 const appearance=document.createElement('details');appearance.className='appearance-settings';appearance.innerHTML='<summary>화면 · 단축키 설정</summary><label>글자 크기<select id="uiFont">'+[12,13,14,15,16,18].map(n=>'<option value="'+n+'">'+n+'px</option>').join('')+'</select></label><label>목록 간격<select id="uiDensity"><option value="compact">간결하게</option><option value="comfortable">넉넉하게</option></select></label><label><input id="uiMinimap" type="checkbox" checked>확대 위치 미니맵</label><p class="help">A 확인 완료 · I 문제 있음 · N 다음 검수 · P 이전 문구 · Space 이미지 이동 · Ctrl+Z 실행 취소. 입력 중에는 검수 단축키가 동작하지 않습니다.</p><p id="preferenceStatus" role="status"></p>';document.querySelector('.workspace-more').append(appearance);for(const id of ['uiFont','uiDensity','uiMinimap'])$(id).onchange=()=>{showPreferences({...UX.preferences,fontSize:Number($('uiFont').value),density:$('uiDensity').value,minimap:$('uiMinimap').checked,layout:document.body.dataset.layout});persistPreferences(true)};
 const map=document.createElement('button');map.id='imageMinimap';map.className='image-minimap';map.type='button';map.setAttribute('aria-label','이미지 전체 위치 · 클릭해 이동');map.innerHTML='<img id="minimapImage" alt=""><span id="minimapView"></span>';$('canvasViewport').parentElement.append(map);map.onclick=e=>{const rect=map.getBoundingClientRect(),f=$('imageFrame'),v=$('canvasViewport');v.scrollLeft=(e.clientX-rect.left)/rect.width*f.clientWidth-v.clientWidth/2;v.scrollTop=(e.clientY-rect.top)/rect.height*f.clientHeight-v.clientHeight/2};$('canvasViewport').addEventListener('scroll',()=>{updateMinimap();if(UX.restoringView)return;captureImageView();clearTimeout(UX.viewTimer);const item=activeItem();UX.viewTimer=setTimeout(()=>{if(item===activeItem()&&item)dirty()},800)});$('preview').addEventListener('load',restoreImageView);new ResizeObserver(updateMinimap).observe($('imageFrame'));const storeView=()=>requestAnimationFrame(()=>{captureImageView();if(activeItem())dirty()});for(const id of ['zoomIn','zoomOut','fitImage','originalImage'])$(id).addEventListener('click',storeView);$('canvasViewport').addEventListener('wheel',event=>{if(event.ctrlKey||event.metaKey)storeView()});
 const regionTools=document.createElement('details');regionTools.className='region-batch-tools';regionTools.innerHTML='<summary>영역 일괄 편집 <span id="regionSelectedCount">0개 선택</span></summary><div class="toolbar"><button id="regionsLock" class="ghost small">잠금</button><button id="regionsUnlock" class="ghost small">잠금 해제</button><button id="regionsHide" class="ghost small">표시 전환</button><button id="regionsDelete" class="danger small">문구 삭제</button></div><div class="toolbar"><label>X 이동(px)<input id="regionsDx" type="number" value="0" min="-5000" max="5000"></label><label>Y 이동(px)<input id="regionsDy" type="number" value="0" min="-5000" max="5000"></label><button id="regionsShift" class="ghost small">선택 영역 이동</button></div><p class="help">잠긴 영역은 이동·삭제에서 보호됩니다. 숨김은 분석 설정에 영향을 주지 않습니다.</p>';$('entries').before(regionTools);for(const [id,kind] of [['regionsLock','lock'],['regionsUnlock','unlock'],['regionsHide','hide'],['regionsDelete','delete'],['regionsShift','shift']])$(id).onclick=()=>regionBatch(kind);new MutationObserver(updateRegionTools).observe($('entries'),{childList:true});
 const layout=document.createElement('label');layout.innerHTML='OCR 읽기 순서<select id="ocrLayout"><option value="raw">원래 인식 순서</option><option value="lines">가로 줄 순서</option><option value="columns">여러 열 순서</option><option value="vertical">세로쓰기 순서</option></select>';$('ocrDraftInfo').before(layout);$('ocrLayout').onchange=()=>{if(F.ocrRawLines?.length)showDraftLines(F.ocrRawLines);if(activeItem()?.payload)$('ocrText').textContent=orderedOcrLines(activeItem().payload.result.lines||[],$('ocrLayout').value).map(l=>l.text).join('\n')};
 const profile=document.createElement('label');profile.innerHTML='<input id="profileInclude" type="checkbox" checked>분석 도구·재확인 옵션·무시 영역 함께 저장';$('savePreset').parentElement.after(profile);
 const baselineControls=document.createElement('div');baselineControls.className='baseline-extra';baselineControls.innerHTML='<label>기준 버전 이름<input id="baselineTag" maxlength="80" placeholder="예: 1.2.0 / 번체 / 2340×1080"></label><div class="toolbar"><button id="baselineCurrent" class="ghost small">현재 이미지를 기준으로 보관</button><button id="baselinePairFiles" class="ghost small">여러 기준 이미지 연결</button><input id="baselineFiles" type="file" accept="image/png,image/jpeg,image/webp" multiple hidden></div><details><summary>기준 이미지 이력 · 최대 10개</summary><div id="baselineHistory"></div></details>';$('baselineInfo').after(baselineControls);$('baselineCurrent').onclick=baselineFromCurrent;$('baselinePairFiles').onclick=()=>$('baselineFiles').click();$('baselineFiles').onchange=e=>{openBaselinePairing(e.target.files);e.target.value=''};featureDialog('baselinePairDialog','기준 이미지 연결 미리보기','<p class="help">확장자를 제외한 파일명이 같은 이미지에 연결합니다. 중복 이름은 적용하지 않습니다.</p><div id="baselinePairPreview"></div><p id="baselinePairError" role="alert"></p><button id="applyBaselinePairs">일치한 이미지에 적용</button>');$('applyBaselinePairs').onclick=applyBaselinePairs;
 const compareExtra=document.createElement('div');compareExtra.className='compare-extra';compareExtra.innerHTML='<div class="toolbar"><label>비교 보기<select id="compareDisplay"><option value="diff">세 화면 / 차이 강조</option><option value="slider">겹쳐 보기 슬라이더</option><option value="blink">기준·현재 번갈아 보기</option></select></label><label>겹쳐 보기<input id="compareBlend" type="range" min="0" max="100" value="50"></label><span id="compareFrameLabel" role="status"></span><button id="cancelCompare" class="danger small" disabled>비교 취소</button><button id="nextChange" class="ghost small" disabled>다음 변경 →</button><span id="changeCount"></span></div><details><summary>변경 위치 목록</summary><div id="changedRegionList"></div></details>';document.querySelector('.compare-images').before(compareExtra);$('compareDisplay').onchange=()=>{comparisonPresentation();if(F.compareOriginals?.diff)fitComparison()};$('compareBlend').oninput=comparisonPresentation;$('cancelCompare').onclick=()=>F.compareController?.abort();$('nextChange').onclick=()=>{const n=activeItem()?.comparison?.regions?.length;if(n)focusChange((UX.changeIndex+1)%n)};$('compareDialog').addEventListener('close',()=>{clearInterval(F.blinkTimer);F.blinkTimer=null;F.compareController?.abort()});
 const elapsed=document.createElement('span');elapsed.id='analysisElapsed';elapsed.setAttribute('role','status');$('progressText').after(elapsed);new MutationObserver(()=>{if($('progressText').closest('.progress').classList.contains('hidden')){clearInterval(UX.elapsedTimer);UX.elapsedTimer=null;return}if(!UX.elapsedTimer){const start=performance.now();UX.elapsedTimer=setInterval(()=>{$('analysisElapsed').textContent='경과 '+Math.floor((performance.now()-start)/1000)+'초'},500)}}).observe($('progressText').closest('.progress'),{attributes:true,attributeFilter:['class']});
 document.addEventListener('keydown',reviewKeyboard);document.addEventListener('keyup',e=>{if(e.key===' '&&UX.previousMode){setCanvasMode(UX.previousMode);UX.previousMode=null}});window.addEventListener('blur',()=>{if(UX.previousMode){setCanvasMode(UX.previousMode);UX.previousMode=null}});
 document.querySelectorAll('.panel-grip').forEach(g=>{g.addEventListener('pointerup',persistPreferences);g.addEventListener('keydown',persistPreferences)});document.querySelectorAll('[data-layout-mode]').forEach(b=>b.addEventListener('click',persistPreferences));
 projectRequest('/api/workspace/preferences').then(p=>{showPreferences(p);UX.preferencesReady=true;$('preferenceStatus').textContent='화면 설정 불러옴'}).catch(e=>{UX.preferencesReady=true;$('preferenceStatus').textContent='화면 설정 불러오기 실패 · '+e.message});
 updateMinimap();updateRegionTools();
}
`;
