export const featureClient=String.raw`
var F={ready:false,excelPlan:null,ocrLines:[],watch:null,watchPolling:false,pixelmatch:null,comparison:null};
const activeItem=()=>W.items.find(i=>i.id===W.active),featureBusy=()=>!!(W.busy||W.operation||S.controller);
const imageRefUrl=ref=>'/api/images?hash='+ref.hash+'&type='+encodeURIComponent(ref.type)+'&size='+ref.size;
async function imageReference(file){const response=await fetch('/api/images',{method:'POST',body:file});const data=await response.json();if(!response.ok)throw Error(data.error?.message||'원본 저장 실패');return data}
async function storedItem(item,backup=false){
 if(!item.imageRef)item.imageRef=await imageReference(item.file);
 const validIds=new Set(item.targets.map(t=>t.id));item.reviewNotes=Object.fromEntries(Object.entries(item.reviewNotes||{}).filter(([id])=>validIds.has(id)));item.reviews=Object.fromEntries(Object.entries(item.reviews||{}).filter(([id])=>validIds.has(id)));const record={id:item.id,name:item.file.name,lastModified:item.file.lastModified,targets:structuredClone(item.targets),payload:structuredClone(item.payload),resultTargets:structuredClone(item.resultTargets),ignoreRegions:structuredClone(item.ignoreRegions||[]),reviews:structuredClone(item.reviews||{}),reviewNotes:structuredClone(item.reviewNotes||{}),view:structuredClone(item.view||null),baselineHistory:structuredClone(item.baselineHistory||[]),baseline:structuredClone(item.baseline||null),comparison:structuredClone(item.comparison||null),problem:item.problem||''};
 if(backup){for(const historical of record.baselineHistory){const r=await fetch(imageRefUrl(historical.image));if(!r.ok)throw Error('기준 이력 백업 실패');historical.data=await encodeFile(await r.blob())}record.data=await encodeFile(item.file);if(record.baseline){const r=await fetch(imageRefUrl(record.baseline.image));if(!r.ok)throw Error('비교 기준 이미지 백업 실패');record.baseline.data=await encodeFile(await r.blob())}}
 else record.image=item.imageRef;
 return record;
}
async function workspaceData(){snapshot();const items=[];for(const item of W.items)items.push(await storedItem(item));return {format:'language-test-workspace',version:1,name:$('workspaceName').value,folder:$('workspaceFolder').value,items,batch:structuredClone(W.batch||null),watchPath:$('watchPath').value}}
function featureDialog(id,title,body){const d=document.createElement('dialog');d.id=id;d.className='workbench-dialog feature-dialog';d.setAttribute('aria-label',title);d.innerHTML='<div class="dialog-heading"><h2>'+title+'</h2><form method="dialog"><button class="ghost small" aria-label="'+title+' 닫기">닫기</button></form></div>'+body;document.querySelector('.app').append(d);return d}
function mountFeatures(){
 const actions=document.createElement('div');actions.className='feature-actions';actions.innerHTML='<p id="watchBadge" role="status"></p>'+'<button id="openReport" class="ghost small">전체 보고서</button><button id="openExcelMap" class="ghost small">엑셀 자동 연결</button><button id="openCompare" class="ghost small">화면 비교</button><button id="openWatcher" class="ghost small">자동 가져오기</button>';$('imageQueue').before(actions);
 featureDialog('reportDialog','전체 작업 보고서','<p>모든 이미지의 자동 판정과 수동 검수를 함께 내보냅니다. HTML에는 원본과 지정 영역 캡처를 포함합니다.</p><p id="reportInfo" role="status"></p><div class="toolbar"><button id="reportXlsx">엑셀 저장</button><button id="reportCsv" class="secondary">CSV 저장</button><button id="reportHtml" class="secondary">HTML 보고서 저장</button></div>');
 featureDialog('excelMapDialog','엑셀 문구 자동 연결','<label>엑셀 파일<input id="mapFile" type="file" accept=".xlsx,.xls,.csv"></label><div class="feature-grid"><label>시트<select id="mapSheet"></select></label><label>파일명 또는 화면명 열<select id="mapKey"></select></label><label>문구 열<select id="mapText"></select></label><label>언어 열<select id="mapLanguage"></select></label><label>기본 언어<select id="mapDefaultLanguage">'+opts('en')+'</select></label><label>표시 이름 열<select id="mapLabel"></select></label><label>검증 방식 열<select id="mapMode"></select></label><label>영역 좌표 열<select id="mapRegion"></select></label></div><p>파일 경로·파일명으로 먼저 연결하며, 확장자를 제외한 이름이나 기존 화면명으로도 연결합니다. 중복 이름은 직접 구분해 주세요. 적용 시 연결된 이미지의 기존 문구를 교체합니다.</p><div class="toolbar"><button id="previewMap" class="secondary">연결 미리보기</button><button id="applyMap" disabled>연결 적용</button><button id="undoMap" class="ghost" disabled>엑셀 연결 되돌리기</button></div><div id="mapPreview" role="status"></div>');
 featureDialog('compareDialog','이전 화면과 비교','<label>작업 목록의 기준 이미지<select id="baselineSelect"></select></label><button id="setBaseline" class="secondary small">선택 이미지로 기준 지정</button><label>외부 기준 이미지<input id="baselineFile" type="file" accept="image/png,image/jpeg,image/webp"></label><p id="baselineInfo"></p><div class="feature-grid"><label>차이 허용치<input id="diffThreshold" type="number" min="0" max="1" step="0.01" value="0.1"></label><label>기준 가로 이동(px)<input id="diffX" type="number" min="-5000" max="5000" value="0"></label><label>기준 세로 이동(px)<input id="diffY" type="number" min="-5000" max="5000" value="0"></label></div><label><input id="diffScale" type="checkbox">기준 이미지 크기를 현재 화면에 맞추기</label><p>FPS·시계·움직이는 배경은 무시 영역으로 제외할 수 있습니다. 화면 비율이 다르면 위치를 먼저 확인하세요.</p><div class="toolbar"><button id="autoAlign" class="secondary">자동으로 위치 맞추기</button><button id="runCompare">차이 확인</button></div><p id="diffInfo" role="status"></p><div class="compare-images"><figure><figcaption>기준</figcaption><canvas id="baselineCanvas"></canvas></figure><figure><figcaption>현재</figcaption><canvas id="currentCanvas"></canvas></figure><figure><figcaption>변경 영역</figcaption><canvas id="diffCanvas"></canvas></figure></div><button id="saveDiff" class="ghost small" disabled>비교 이미지 저장</button>');
 featureDialog('watchDialog','폴더 자동 가져오기','<label>이미지 폴더 경로<input id="watchPath" placeholder="이미지가 저장되는 폴더" maxlength="1000"></label><div class="toolbar"><button id="pickWatchFolder" class="ghost small">폴더 선택</button><button id="startWatch">자동 가져오기 시작</button><button id="stopWatch" class="ghost" disabled>중지</button></div><label><input id="watchExisting" type="checkbox">폴더의 기존 이미지도 가져오기</label><label><input id="watchCopy" type="checkbox">현재 이미지의 문구·영역·무시 영역을 새 이미지에 적용</label><p>앱이 열려 있는 동안 3초마다 확인합니다. 파일 크기가 안정된 새 PNG·JPG·WebP를 가져옵니다. 하위 폴더는 4단계까지 포함합니다. 앱 재실행 후 시작 버튼으로 다시 연결하세요.</p><p id="watchInfo" role="status">자동 가져오기 꺼짐</p>');
 featureDialog('ocrDraftDialog','OCR에서 검증 항목 만들기','<p>선택한 글자를 기대 문구와 영역으로 추가합니다. 정답 문구를 직접 확인한 뒤 검증하세요.</p><label>문구 언어<select id="ocrDraftLanguage">'+opts('en')+'</select></label><div class="toolbar"><button id="readDraftOcr" class="secondary">이미지 글자 읽기</button><button id="addDraftTargets" disabled>선택 문구 추가</button></div><p id="ocrDraftInfo" role="status"></p><div id="ocrDraftLines"></div>');
 const tools=document.createElement('div');tools.className='feature-inspector-tools';tools.innerHTML='<button id="openOcrDraft" class="ghost small">OCR에서 문구 만들기</button><button id="addIgnoreRegion" class="ghost small">무시 영역 그리기</button><div id="ignoreList"></div>';$('entries').before(tools);
 const review=document.createElement('section');review.id='manualReviewPanel';review.className='manual-review';$('resultCard').append(review);
 const batch=document.createElement('div');batch.className='batch-checkpoint';batch.innerHTML='<button id="pauseBatch" class="ghost small" disabled>현재 이미지 후 일시정지</button><button id="resumeBatch" class="secondary small" disabled>남은 이미지 이어서 검증</button><p id="batchInfo" role="status"></p>';document.querySelector('.batch-more').append(batch);
 const mask=document.createElement('div');mask.id='ignoreLayer';$('imageFrame').append(mask);
 $('openReport').onclick=()=>{snapshot();const rows=reportRows(W.items);$('reportInfo').textContent=W.items.length+'장 · '+(rows.length-1)+'개 검증 문구';$('reportDialog').showModal()};
 $('reportCsv').onclick=()=>download(reportName()+'.csv',csvReport(reportRows(W.items)),'text/csv;charset=utf-8');
 $('reportXlsx').onclick=()=>{const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(reportRows(W.items)),'전체 검증');XLSX.writeFile(book,reportName()+'.xlsx')};$('reportHtml').onclick=exportHtmlReport;
 $('openExcelMap').onclick=()=>$('excelMapDialog').showModal();$('mapFile').onchange=readMapFile;$('mapSheet').onchange=mapColumns;['mapKey','mapText','mapLanguage','mapDefaultLanguage','mapLabel','mapMode','mapRegion'].forEach(id=>$(id).onchange=()=>{F.excelPlan=null;$('applyMap').disabled=true;$('mapPreview').textContent='연결 미리보기를 다시 확인하세요.'});$('previewMap').onclick=previewMap;$('applyMap').onclick=applyMap;$('undoMap').onclick=undoMap;
 $('openCompare').onclick=()=>{const item=activeItem();$('baselineSelect').innerHTML=W.items.filter(i=>i!==item).map(i=>'<option value="'+i.id+'">'+esc(i.file.name)+'</option>').join('');resetComparisonView();$('diffThreshold').value=item?.baseline?.threshold??.1;$('baselineInfo').textContent=item?.baseline?'저장된 기준: '+item.baseline.name:'기준 이미지를 선택하세요.';$('diffInfo').textContent='';$('saveDiff').disabled=true;$('diffX').value=item?.baseline?.x||0;$('diffY').value=item?.baseline?.y||0;$('diffScale').checked=!!item?.baseline?.scale;refreshBaselineHistory();$('compareDialog').showModal()};
 $('setBaseline').onclick=async()=>{const source=W.items.find(i=>i.id===$('baselineSelect').value);if(source)await setBaselineFile(source.file)};$('baselineFile').onchange=async event=>{const file=event.target.files[0];if(file)await setBaselineFile(file);event.target.value=''};$('autoAlign').onclick=autoAlign;$('runCompare').onclick=runComparison;['diffThreshold','diffX','diffY','diffScale'].forEach(id=>{$(id).oninput=resetComparisonView;$(id).onchange=resetComparisonView});$('saveDiff').onclick=()=>$('diffCanvas').toBlob(blob=>blob&&download(reportName()+'-compare.png',blob,'image/png'));
 $('openWatcher').onclick=()=>$('watchDialog').showModal();$('watchPath').oninput=()=>{if(W.items.length)dirty()};$('pickWatchFolder').onclick=async()=>{try{$('pickWatchFolder').disabled=true;const result=await projectRequest('/api/watch/pick',{});if(result.path)$('watchPath').value=result.path}catch(e){$('watchInfo').textContent=e.message}finally{$('pickWatchFolder').disabled=false}};$('startWatch').onclick=startWatch;$('stopWatch').onclick=stopWatch;
 $('openOcrDraft').onclick=()=>{snapshot();F.ocrLines=[];$('ocrDraftLines').replaceChildren();$('addDraftTargets').disabled=true;$('ocrDraftInfo').textContent='글자를 읽거나 현재 검증 결과에서 가져올 수 있습니다.';$('ocrDraftLanguage').value=activeItem()?.targets.find(t=>t.text)?.language||'en';const lines=activeItem()?.payload?.result?.lines;if(lines?.length)showDraftLines(lines);$('ocrDraftDialog').showModal()};$('readDraftOcr').onclick=readDraftOcr;$('addDraftTargets').onclick=addDraftTargets;
 $('addIgnoreRegion').onclick=()=>{if(featureBusy()||!activeItem())return;if((activeItem().ignoreRegions||[]).length>=40)return error('무시 영역은 40개까지 지정하세요.');F.ignoreDrawing=true;setWorkbenchTab('settings');setCanvasMode('select');$('canvasHint').textContent='드래그하여 검증에서 제외할 영역 지정';document.body.classList.add('drawing-ignore')};
 $('imageFrame').addEventListener('pointerdown',beginIgnore,true);$('imageFrame').addEventListener('pointermove',moveIgnore,true);$('imageFrame').addEventListener('pointerup',endIgnore,true);$('imageFrame').addEventListener('pointercancel',cancelIgnore,true);
 document.addEventListener('keydown',event=>{if(event.key==='Escape')cancelIgnore()});
 $('pauseBatch').onclick=()=>{W.pauseRequested=true;$('pauseBatch').disabled=true;$('batchInfo').textContent='현재 이미지가 끝나면 일시정지합니다.'};$('resumeBatch').onclick=resumeStoredBatch;
 const storage=document.createElement('section');storage.innerHTML='<h3>원본 저장 공간</h3><p id="storageInfo" role="status">사용량 확인을 눌러 주세요.</p><div class="toolbar"><button id="checkStorage" class="ghost small">사용량 확인</button><button id="cleanStorage" class="ghost small" disabled>사용하지 않는 원본 정리</button></div><p class="help">저장 작업·임시 작업·휴지통에서 사용 중인 원본은 유지합니다. 참조가 없고 24시간이 지난 파일만 정리합니다.</p>';$('workbenchSettings').append(storage);$('checkStorage').onclick=refreshStorageInfo;$('cleanStorage').onclick=cleanStorage;F.ready=true;refreshFeatures();
}
async function refreshStorageInfo(){try{const data=await projectRequest('/api/workspace/storage');$('storageInfo').textContent='원본 '+data.files+'개 · '+(data.bytes/1048576).toFixed(1)+'MB · 정리 가능 '+data.unusedFiles+'개 ('+(data.unusedBytes/1048576).toFixed(1)+'MB)';$('cleanStorage').disabled=!data.unusedFiles}catch(e){$('storageInfo').textContent=e.message;$('cleanStorage').disabled=true}}
async function cleanStorage(){if(featureBusy()||!confirm('사용 중인 작업에서 참조하지 않는 24시간 이상 된 원본 파일만 정리할까요?'))return;const unlock=lockWorkspace();try{const result=await projectRequest('/api/workspace/storage/clean',{});await refreshStorageInfo();$('storageInfo').textContent+=' · '+result.removedFiles+'개 정리 완료'}catch(e){$('storageInfo').textContent=e.message}finally{unlock()}}
async function autoAlign(){if(featureBusy())return;const item=activeItem();if(!item?.baseline)return $('diffInfo').textContent='기준 이미지를 먼저 지정하세요.';const unlock=lockWorkspace();$('autoAlign').disabled=true;resetComparisonView();$('diffInfo').textContent='화면 위치를 자동으로 찾는 중…';try{if(!item.imageRef)item.imageRef=await imageReference(item.file);const result=await projectRequest('/api/compare/align',{before:item.baseline.image,after:item.imageRef,ignore:item.ignoreRegions||[],scale:$('diffScale').checked});$('diffX').value=result.x;$('diffY').value=result.y;$('diffInfo').textContent='자동 보정: 가로 '+result.x+'px · 세로 '+result.y+'px · 차이 확인을 눌러 결과를 확인하세요.'}catch(e){$('diffInfo').textContent=e.message}finally{unlock();$('autoAlign').disabled=false}}
function resetComparisonView(){clearInterval(F.blinkTimer);F.blinkTimer=null;F.compareOriginals=null;if($('changedRegionList'))$('changedRegionList').replaceChildren();if($('nextChange'))$('nextChange').disabled=true;if(!$('diffCanvas'))return;for(const id of ['baselineCanvas','currentCanvas','diffCanvas']){const c=$(id);c.getContext('2d').clearRect(0,0,c.width,c.height)}$('saveDiff').disabled=true;$('diffInfo').textContent='설정에 맞춰 차이 확인을 눌러 주세요.'}
function undoMap(){if(featureBusy()||!F.mapUndo||F.mapUndo.draftId!==W.draftId)return;for(const saved of F.mapUndo.items){const item=W.items.find(i=>i.id===saved.id);if(item)Object.assign(item,structuredClone(saved))}F.mapUndo=null;$('undoMap').disabled=true;const id=W.active;W.active=null;S.last=null;activate(id);dirty();queue();$('mapPreview').textContent='이전 문구와 결과로 되돌렸습니다.'}
function reportName(){return ($('workspaceName').value.trim()||'Language Test')+'-전체검증'}
async function exportHtmlReport(){
 const unlock=lockWorkspace();$('reportHtml').disabled=true;try{
  snapshot();let content='';const rows=reportRows(W.items);$('reportInfo').textContent='이미지와 영역 캡처를 보고서에 넣는 중…';
  for(const item of W.items){const thumb=await historyImage(item.file),url=await encodeFile(thumb);let entries='';let bitmap;
   try{bitmap=await createImageBitmap(item.file);for(const t of item.targets.filter(t=>t.text)){const r=item.payload?.result?.results.find(r=>r.id===t.id),m=manualState(item,t.id),area=t.region||r?.evidence?.[0]?.boundingBox||r?.nearestEvidence?.[0]?.boundingBox;let crop='';if(area){const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.ceil(area.width*bitmap.width));canvas.height=Math.max(1,Math.ceil(area.height*bitmap.height));canvas.getContext('2d').drawImage(bitmap,area.x*bitmap.width,area.y*bitmap.height,area.width*bitmap.width,area.height*bitmap.height,0,0,canvas.width,canvas.height);crop='<img class="crop" alt="검증 영역" src="'+canvas.toDataURL('image/webp',.85)+'">'}entries+='<article><h3>'+esc(t.label||t.text)+'</h3><p>'+esc(t.language)+' · 자동: '+(r?r.found?'통과':r.reviewRequired?'확인 필요':'미통과':'미검증')+' · 수동: '+(m?m.verdict==='accepted'?'확인 완료':'문제 있음':'검수 전')+'</p><p>기대: '+esc(t.text)+'</p><p>OCR: '+esc(r?.observedText||r?.matchedText||'')+'</p><p>'+esc(r?.reason||'')+'</p>'+crop+((item.reviewNotes?.[t.id]?.note||m?.note)?'<p>검수 메모: '+esc(item.reviewNotes?.[t.id]?.note??m.note)+' · '+esc(item.reviewNotes?.[t.id]?.at??m.at)+'</p>':'')+'</article>'}}finally{bitmap?.close()}
   content+='<section><h2>'+esc(item.file.name)+'</h2><img class="source" alt="원본 미리보기" src="'+url+'">'+entries+'</section>';
  }
  const html='<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; img-src data:; style-src \'unsafe-inline\'"><title>'+esc(reportName())+'</title><style>body{font:15px system-ui;max-width:1100px;margin:32px auto;padding:0 20px;color:#17213d}section{border-top:2px solid #cad2e4;margin-top:32px}article{padding:16px;border:1px solid #d6ddeb;margin:12px 0;break-inside:avoid}p{white-space:pre-wrap}.source{max-width:100%;max-height:420px}.crop{max-width:100%;max-height:200px}@media print{section{break-before:page}}</style><h1>'+esc(reportName())+'</h1><p>'+W.items.length+'장 · '+(rows.length-1)+'개 문구 · '+new Date().toLocaleString('ko-KR')+'</p>'+content+'</html>';
  download(reportName()+'.html',html,'text/html;charset=utf-8');$('reportInfo').textContent='HTML 저장 요청 완료 · 다운로드 폴더에서 확인하세요.';
 }catch(e){$('reportInfo').textContent=e.message}finally{unlock();$('reportHtml').disabled=false}
}
async function readMapFile(event){try{const file=event.target.files[0];if(!file)return;if(file.size>8388608)throw Error('엑셀은 8MB 이하로 선택하세요.');F.mapBook=XLSX.read(await file.arrayBuffer(),{type:'array'});$('mapSheet').innerHTML=F.mapBook.SheetNames.map(s=>'<option>'+esc(s)+'</option>').join('');mapColumns()}catch(e){$('mapPreview').textContent=e.message}}
function mapColumns(){F.excelPlan=null;$('applyMap').disabled=true;const sheet=F.mapBook?.Sheets[$('mapSheet').value];if(!sheet)return;F.mapRows=XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:false});const headers=F.mapRows[0]||[];for(const id of ['mapKey','mapText','mapLanguage','mapLabel','mapMode','mapRegion'])$(id).innerHTML=colopts(headers,!['mapKey','mapText'].includes(id));
 const pick=(id,names)=>{const n=headers.findIndex(h=>names.includes(String(h).trim().toLowerCase()));if(n>=0)$(id).value=String(n)};pick('mapKey',['파일명','파일','filename','file','screen','화면명']);pick('mapText',['문구','text','phrase','ko','en','ja','zh-tw','zh-cn']);pick('mapLanguage',['언어','language','lang']);pick('mapLabel',['표시 이름','label']);pick('mapMode',['mode','방식','검증 방식']);pick('mapRegion',['region','bbox','영역','영역 좌표']);$('mapPreview').textContent='열을 선택하고 연결 미리보기를 확인하세요.';
}
function previewMap(){try{if(!F.mapRows?.length)throw Error('엑셀 파일을 선택하세요.');snapshot();const plan=excelAssignments(W.items,F.mapRows.slice(1),{keyColumn:$('mapKey').value,textColumn:$('mapText').value,languageColumn:$('mapLanguage').value,labelColumn:$('mapLabel').value,modeColumn:$('mapMode').value,regionColumn:$('mapRegion').value,language:$('mapDefaultLanguage').value});F.excelPlan=plan;$('mapPreview').innerHTML='<p>연결 '+plan.plan.length+'개 · 이미지 '+new Set(plan.plan.map(p=>p.itemId)).size+'장 · 연결 안 됨 '+plan.unmatched.length+'행 · 이름 중복 '+plan.ambiguous.length+'행 · 오류 '+plan.errors.length+'행</p>'+[['연결 안 됨',plan.unmatched],['이름 중복',plan.ambiguous],['입력 오류',plan.errors]].filter(x=>x[1].length).map(([name,rows])=>'<p>'+name+': '+esc(rows.join(', '))+'</p>').join('')+'<div class="map-list">'+plan.plan.slice(0,200).map(p=>'<p>행 '+p.row+' → '+esc(W.items.find(i=>i.id===p.itemId)?.file.name)+' · '+esc(p.target.language)+' · '+esc(p.target.text)+'</p>').join('')+'</div>';$('applyMap').disabled=!plan.plan.length||!!plan.ambiguous.length||!!plan.errors.length}catch(e){$('mapPreview').textContent=e.message;$('applyMap').disabled=true}}
function applyMap(){if(featureBusy()||!F.excelPlan)return;snapshot();const plan=F.excelPlan;F.mapUndo={draftId:W.draftId,items:W.items.filter(i=>plan.plan.some(p=>p.itemId===i.id)).map(i=>({id:i.id,targets:structuredClone(i.targets),payload:structuredClone(i.payload),resultTargets:structuredClone(i.resultTargets),problem:i.problem}))};$('undoMap').disabled=false;for(const id of new Set(plan.plan.map(p=>p.itemId))){const item=W.items.find(i=>i.id===id);if(!item)continue;item.targets=plan.plan.filter(p=>p.itemId===id).map(p=>({...p.target,id:crypto.randomUUID()}));item.payload=null;item.resultTargets=[];item.problem='엑셀 연결 · 재검증 필요'}if(plan.plan.some(p=>p.itemId===W.active)){const id=W.active;W.active=null;S.last=null;activate(id)}dirty();queue();$('excelMapDialog').close();$('workspaceStatus').textContent=new Set(plan.plan.map(p=>p.itemId)).size+'장에 엑셀 문구를 연결했습니다.';F.excelPlan=null}
function refreshFeatureResults(){if(F?.ready&&typeof UX!=='undefined'&&UX.ready){reviewDetail();if(UX.enhanced)updateRegionTools()}}
async function saveManualReview(verdict){if(featureBusy())return false;const item=activeItem(),id=S.selectedResult,note=$('reviewNote').value,unlock=lockWorkspace();let saved=false;try{if(!item.imageRef)item.imageRef=await imageReference(item.file);item.reviews=Object.fromEntries(Object.entries(item.reviews||{}).filter(([key])=>item.targets.some(t=>t.id===key)));item.reviews[id]={verdict,note,at:new Date().toISOString(),signature:reviewSignature(item,id)};reviewNote(item,id,note);UX.notes.delete(W.active+':'+id);dirty();queue();saved=true}catch(e){error(e.message)}finally{unlock();refreshFeatureResults()}return saved}
async function setBaselineFile(file){if(featureBusy())return;const unlock=lockWorkspace();try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10485760)throw Error('기준 이미지는 10MB 이하 PNG·JPG·WebP로 선택하세요.');const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>64000000){bitmap.close();throw Error('기준 이미지 해상도가 너무 큽니다.')}const size={width:bitmap.width,height:bitmap.height};bitmap.close();const item=activeItem();if(item.baseline&&!item.baselineHistory?.length)rememberBaseline(item,item.baseline);rememberBaseline(item,{name:file.name,image:await imageReference(file),width:size.width,height:size.height,x:0,y:0,scale:false});refreshBaselineHistory();activeItem().comparison=null;resetComparisonView();dirty();$('baselineInfo').textContent='기준 저장: '+file.name}catch(e){$('baselineInfo').textContent=e.message}finally{unlock()}}
async function runComparison(){if(featureBusy())return;const item=activeItem();if(!item?.baseline)return $('diffInfo').textContent='기준 이미지를 먼저 지정하세요.';const threshold=Number($('diffThreshold').value),dx=Number($('diffX').value),dy=Number($('diffY').value);if(!Number.isFinite(threshold)||threshold<0||threshold>1||!Number.isInteger(dx)||!Number.isInteger(dy)||Math.abs(dx)>5000||Math.abs(dy)>5000)return $('diffInfo').textContent='허용치는 0~1, 이동은 -5000~5000 정수로 입력하세요.';const unlock=lockWorkspace();resetComparisonView();F.compareController=new AbortController();$('cancelCompare').disabled=false;$('runCompare').disabled=true;let before,after;
 try{$('diffInfo').textContent='화면 차이 계산 중…';const response=await fetch(imageRefUrl(item.baseline.image));if(!response.ok)throw Error('기준 이미지를 읽지 못했습니다.');before=await createImageBitmap(await response.blob());after=await createImageBitmap(item.file);const scale=$('diffScale').checked;if(!scale&&(before.width!==after.width||before.height!==after.height))throw Error('해상도가 다릅니다. 크기 맞추기를 선택하거나 같은 해상도의 기준을 사용하세요.');const region=$('compareScope').value==='region'?selectedArea(S.last?.result?.results?.find(r=>r.id===S.selectedResult))||activeItem()?.targets.find(t=>t.id===UI.regionId)?.region:null;if($('compareScope').value==='region'&&!region)throw Error('문구나 검증 영역을 먼저 선택하세요.');const area=comparisonArea(after.width,after.height,region),ratio=area.ratio,width=Math.max(1,Math.round(area.width*ratio)),height=Math.max(1,Math.round(area.height*ratio));
 const canvases=['baselineCanvas','currentCanvas','diffCanvas'].map(id=>$(id));for(const c of canvases){c.width=width;c.height=height}const [a,b,c]=canvases.map(c=>c.getContext('2d',{willReadFrequently:true}));a.fillStyle='white';a.fillRect(0,0,width,height);const sx=scale?after.width/before.width:1,sy=scale?after.height/before.height:1;a.drawImage(before,(area.x-dx)/sx,(area.y-dy)/sy,area.width/sx,area.height/sy,0,0,width,height);b.drawImage(after,area.x,area.y,area.width,area.height,0,0,width,height);const ai=a.getImageData(0,0,width,height),bi=b.getImageData(0,0,width,height),out=c.createImageData(width,height);
 for(const r of item.ignoreRegions||[]){const x=Math.max(0,Math.floor((r.x*after.width-area.x)*ratio)),y=Math.max(0,Math.floor((r.y*after.height-area.y)*ratio)),endX=Math.min(width,Math.ceil(((r.x+r.width)*after.width-area.x)*ratio)),endY=Math.min(height,Math.ceil(((r.y+r.height)*after.height-area.y)*ratio));for(let yy=y;yy<endY;yy++)for(let xx=x;xx<endX;xx++){const p=(yy*width+xx)*4;ai.data.set(bi.data.subarray(p,p+4),p)}}
 F.compareController.signal.throwIfAborted();F.compareOriginals={before:cloneCanvas($('baselineCanvas')),after:cloneCanvas($('currentCanvas'))};const calculated=await diffInWorker(ai.data,bi.data,width,height,threshold,F.compareController.signal),changed=calculated.changed;out.data.set(new Uint8ClampedArray(calculated.mask));c.drawImage(after,area.x,area.y,area.width,area.height,0,0,width,height);const overlay=document.createElement('canvas');overlay.width=width;overlay.height=height;overlay.getContext('2d').putImageData(out,0,0);c.drawImage(overlay,0,0);item.baseline={...item.baseline,x:dx,y:dy,scale,threshold};item.comparison={changed,total:width*height,ratio:changed/(width*height),regions:calculated.regions,totalRegions:calculated.totalRegions,width,height,at:new Date().toISOString()};dirty();$('diffInfo').textContent='변경 '+(changed/(width*height)*100).toFixed(2)+'% · '+changed.toLocaleString()+'픽셀 · 비교 크기 '+width+'×'+height+' · 무시 영역 '+(item.ignoreRegions||[]).length+'곳';$('saveDiff').disabled=false;F.compareOriginals.diff=cloneCanvas($('diffCanvas'));refreshChangedRegions();comparisonPresentation();fitComparison();
 }catch(e){$('diffInfo').textContent=e.message}finally{before?.close();after?.close();F.compareController=null;$('cancelCompare').disabled=true;$('runCompare').disabled=false;unlock()}
}
function paintIgnored(ctx,regions,width,height,{x=0,y=0,scale=1}={}){ctx.fillStyle='white';for(const r of regions)ctx.fillRect((r.x*width-x)*scale,(r.y*height-y)*scale,r.width*width*scale,r.height*height*scale)}
async function maskedFile(file,regions){const bitmap=await createImageBitmap(file);try{const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const ctx=canvas.getContext('2d');ctx.drawImage(bitmap,0,0);paintIgnored(ctx,regions,bitmap.width,bitmap.height);let blob=await new Promise(r=>canvas.toBlob(r,'image/png'));if(blob.size>10485760)blob=await new Promise(r=>canvas.toBlob(r,'image/webp',.95));if(blob.size>10485760)throw Error('무시 영역 처리 이미지가 너무 큽니다. 영역을 지정해 검증하세요.');return new File([blob],file.name,{type:blob.type,lastModified:file.lastModified})}finally{bitmap.close()}}
async function readDraftOcr(){if(featureBusy())return;const item=activeItem();if(!item)return;const unlock=lockWorkspace();S.controller=new AbortController();$('readDraftOcr').disabled=true;try{$('ocrDraftInfo').textContent='이미지 글자를 읽는 중…';const ignored=item.ignoreRegions||[],file=ignored.length?await maskedFile(item.file,ignored):item.file;const payload=await requestOcr(file,[{id:'ocr-draft',text:'OCR',language:$('ocrDraftLanguage').value,mode:'exact',region:{x:0,y:0,width:1,height:1}}],S.controller.signal,false,$('cloudProject').value,ignored);showDraftLines(payload.result.lines)}catch(e){$('ocrDraftInfo').textContent=e.message}finally{S.controller=null;unlock();$('readDraftOcr').disabled=false}}
function showDraftLines(lines){F.ocrRawLines=[...lines];F.ocrLines=orderedOcrLines(lines,$('ocrLayout')?.value||'raw').filter(l=>l.text&&l.boundingBox&&!excludedLine(l,activeItem()?.ignoreRegions||[])).slice(0,1200);$('ocrDraftLines').innerHTML=F.ocrLines.map((l,i)=>'<label class="ocr-line"><input type="checkbox" data-ocr-index="'+i+'"><span>'+esc(l.text)+'</span><small>'+Math.round(l.confidence*100)+'%</small></label>').join('');$('ocrDraftInfo').textContent=F.ocrLines.length+'개 문구 · 필요한 글자를 선택하세요.';$('ocrDraftLines').onchange=()=>$('addDraftTargets').disabled=!$('ocrDraftLines').querySelector('input:checked');$('addDraftTargets').disabled=true}
function addDraftTargets(){if(featureBusy())return;const lines=[...$('ocrDraftLines').querySelectorAll('input:checked')].map(i=>F.ocrLines[Number(i.dataset.ocrIndex)]);const rows=[...$('entries').children].map(read).filter(t=>t.text);if(rows.length+lines.length>80)return $('ocrDraftInfo').textContent='이미지의 검증 문구는 80개 이하로 선택하세요.';for(const row of [...$('entries').children])if(!read(row).text)row.remove();for(const line of lines)add({text:line.text,language:$('ocrDraftLanguage').value,mode:'exact',region:line.boundingBox});edited();snapshot();$('ocrDraftDialog').close();setWorkbenchTab('settings')}
function beginIgnore(event){if(!F.ignoreDrawing||event.button!==0||featureBusy())return;event.preventDefault();event.stopImmediatePropagation();F.ignoreStart={point:point(event),pointer:event.pointerId};$('imageFrame').setPointerCapture(event.pointerId);const box=document.createElement('div');box.id='ignoreDraftBox';box.className='ignore-box';$('ignoreLayer').append(box)}
function moveIgnore(event){if(!F.ignoreStart||event.pointerId!==F.ignoreStart.pointer)return;event.preventDefault();event.stopImmediatePropagation();const p=point(event),a=F.ignoreStart.point;F.ignoreArea={x:Math.min(a.x,p.x),y:Math.min(a.y,p.y),width:Math.abs(a.x-p.x),height:Math.abs(a.y-p.y)};const r=F.ignoreArea,box=$('ignoreDraftBox');if(box)box.style.cssText='left:'+r.x*100+'%;top:'+r.y*100+'%;width:'+r.width*100+'%;height:'+r.height*100+'%'}
function endIgnore(event){if(!F.ignoreStart||event.pointerId!==F.ignoreStart.pointer)return;moveIgnore(event);const area=F.ignoreArea,rect=$('imageFrame').getBoundingClientRect();if(area&&area.width*rect.width>=3&&area.height*rect.height>=3){const item=activeItem();rememberEdit();item.ignoreRegions||=[];item.ignoreRegions.push(area);invalidateFeatureImage(item,'무시 영역 변경 · 재검증 필요');dirty()}cancelIgnore();queue()}
function cancelIgnore(){if(!F?.ignoreDrawing)return;const pointer=F.ignoreStart?.pointer;F.ignoreStart=null;F.ignoreArea=null;F.ignoreDrawing=false;document.body.classList.remove('drawing-ignore');if(pointer!=null&&$('imageFrame').hasPointerCapture(pointer))$('imageFrame').releasePointerCapture(pointer);$('ignoreDraftBox')?.remove();setCanvasMode('select');refreshFeatures()}
function invalidateFeatureImage(item,message){item.comparison=null;resetComparisonView();item.payload=null;item.resultTargets=[];item.problem=message;if(item.id===W.active)resetResult()}
function refreshFeatures(){
 const busy=featureBusy(),item=activeItem();$('watchBadge').textContent=F.watch?'폴더 자동 가져오기 켜짐':'';for(const id of ['openReport','openExcelMap','openCompare','openOcrDraft','addIgnoreRegion'])$(id).disabled=busy||!item;
 $('pauseBatch').disabled=!W.busy||!!W.pauseRequested;$('resumeBatch').disabled=busy||!W.batch||W.batch.status==='complete';if(W.batch&&F.batchIds!==W.batch.ids.join('|')){F.batchIds=W.batch.ids.join('|');document.querySelector('.batch-more').open=W.batch.status!=='complete'}$('batchInfo').textContent=W.batch?(W.batch.status==='complete'?'일괄 검증 완료':W.busy?'일괄 검증 중':'이어갈 작업 있음')+' · '+Object.keys(W.batch.done||{}).length+'/'+W.batch.ids.length+'장 처리':'';
 const reviewKey=[W.active,S.last?.id,S.selectedResult,busy].join('|');if(F.reviewKey!==reviewKey){F.reviewKey=reviewKey;refreshFeatureResults()}
 const regions=item?.ignoreRegions||[];$('ignoreList').innerHTML=regions.map((r,i)=>'<span class="ignore-label">무시 '+(i+1)+' <button data-remove-ignore="'+i+'" class="ghost small" aria-label="무시 영역 '+(i+1)+' 삭제"'+(busy?' disabled':'')+'>×</button></span>').join('');$('ignoreLayer').innerHTML=regions.map((r,i)=>'<div class="ignore-box" style="left:'+r.x*100+'%;top:'+r.y*100+'%;width:'+r.width*100+'%;height:'+r.height*100+'%">무시 '+(i+1)+'</div>').join('');$('ignoreList').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(featureBusy())return;rememberEdit();item.ignoreRegions.splice(Number(b.dataset.removeIgnore),1);invalidateFeatureImage(item,'무시 영역 변경 · 재검증 필요');dirty();queue()});
}
async function startWatch(){try{if(featureBusy())return;F.watch=await projectRequest('/api/watch/start',{path:$('watchPath').value,includeExisting:$('watchExisting').checked});F.watch.draftId=W.draftId;$('watchPath').value=F.watch.path;$('watchInfo').textContent='자동 가져오기 켜짐 · '+F.watch.path;$('startWatch').disabled=true;$('stopWatch').disabled=false;clearInterval(F.watchTimer);F.watchTimer=setInterval(pollWatch,3000);if(W.items.length)dirty();refreshFeatures();await pollWatch()}catch(e){$('watchInfo').textContent=e.message}}
async function stopWatch(){clearInterval(F.watchTimer);F.watch=null;await projectRequest('/api/watch/stop',{}).catch(()=>{});$('startWatch').disabled=false;$('stopWatch').disabled=true;$('watchInfo').textContent='자동 가져오기 꺼짐';refreshFeatures()}
async function pollWatch(){if(!F.watch||F.watchPolling||featureBusy())return;if(F.watch.draftId!==W.draftId){await stopWatch();return;}F.watchPolling=true;const session=F.watch;let unlock=null;try{const list=await projectRequest('/api/watch/poll',{id:session.id});if(F.watch!==session)return;const room=200-W.items.length;if(!room&&list.files.length){$('watchInfo').textContent='200장 제한 · 새 작업을 만든 뒤 가져오세요.';return}const capacity=512*1024*1024-W.items.reduce((n,i)=>n+i.file.size,0),available=[];let used=0;for(const f of list.files.slice(0,room))if(used+f.size<=capacity){available.push(f);used+=f.size}if(!available.length){if(list.pending)$('watchInfo').textContent='남은 이미지 '+list.pending+'장 · 작업 용량을 확인하세요.';return}snapshot();const source=$('watchCopy').checked?activeItem():null,template=source?{targets:structuredClone(source.targets),ignoreRegions:structuredClone(source.ignoreRegions||[]),size:await imageSize(source)}:null;const files=[];for(const f of available){const response=await fetch('/api/watch/files?id='+session.id+'&key='+f.key);if(!response.ok)throw Error('이미지 저장이 끝나면 다시 가져옵니다.');const blob=await response.blob();files.push(new File([blob],f.name,{type:f.type}))}if(F.watch!==session||session.draftId!==W.draftId||featureBusy())return;const before=new Set(W.items.map(i=>i.id));if(!await addImages(files))throw Error('이미지를 추가하지 못했습니다.');unlock=lockWorkspace();if(template)for(const item of W.items.filter(i=>!before.has(i.id))){const size=await imageSize(item),mismatch=regionCopy(template.size,size,template.targets).mismatch;item.targets=regionCopy(template.size,size,template.targets,{omitRegions:mismatch}).targets.map(t=>({...t,id:crypto.randomUUID()}));item.ignoreRegions=mismatch?[]:structuredClone(template.ignoreRegions)}const current=activeItem();if(template&&current){W.active=null;S.last=null;activate(current.id)}dirty();const checkpoint=await saveDraft(true);if(!checkpoint?.ok||!checkpoint.saved){await stopWatch();throw Error('새 이미지 저장에 실패해 자동 가져오기를 중지했습니다. 앱에 저장한 뒤 다시 시작하세요.')}await projectRequest('/api/watch/ack',{id:session.id,keys:available.map(f=>f.key)});$('watchInfo').textContent=available.length+'장 추가 · 남은 '+Math.max(0,list.pending-available.length)+'장 · '+new Date().toLocaleTimeString('ko-KR')}catch(e){$('watchInfo').textContent='자동 가져오기 대기 · '+e.message}finally{unlock?.();F.watchPolling=false}}
async function resumeStoredBatch(){if(featureBusy()||!W.batch)return;$('cloudProject').value=W.batch.provider;$('analysisMode').value=W.batch.mode;$('autoReviewProvider').value=W.batch.autoReview;$('autoReview').checked=W.batch.autoReview!=='off';await refreshConnection();return runBatch('resume')}
function batchSignature(item){return JSON.stringify({targets:item.targets.filter(t=>t.text),ignore:item.ignoreRegions||[],provider:W.batch?.provider,mode:W.batch?.mode,autoReview:W.batch?.autoReview})}
async function runBatch(kind='all',{skipMissing=false}={}){
 if(featureBusy())return;if(!S.authenticated)return error('선택한 도구에 먼저 로그인하세요.');snapshot();
 let items;if(kind==='resume'){
  if(!W.batch)return;items=W.batch.ids.map(id=>W.items.find(i=>i.id===id)).filter(i=>i&&(!i.payload||W.batch.done[i.id]!==batchSignature(i)));
  if($('cloudProject').value!==W.batch.provider||$('analysisMode').value!==W.batch.mode||$('autoReviewProvider').value!==W.batch.autoReview)return error('이어 실행하려면 분석 도구와 옵션을 이전 작업과 같게 선택하세요.');
 }else{items=W.items.filter(item=>kind==='selected'?item.selected:kind==='pending'?needsAttention(item):true)}
 if(skipMissing)items=items.filter(i=>i.targets.some(t=>t.text.trim()));if(!items.length){if(kind==='resume'&&W.batch){W.batch.status='complete';dirty();await saveDraft()}return error('검증할 이미지가 없습니다.')}if(items.some(i=>!i.targets.some(t=>t.text)))return error('검증할 모든 이미지에 문구를 입력하세요.');if(kind!=='resume')W.batch={ids:items.map(i=>i.id),done:{},status:'paused',provider:$('cloudProject').value,mode:$('analysisMode').value,autoReview:$('autoReviewProvider').value};
 W.batch.status='running';W.busy=true;W.cancel=false;W.pauseRequested=false;const unlock=lockWorkspace();let completed=0,checkpointError=null;
 try{dirty();if(!(await saveDraft(true))?.ok)throw Error('이어 실행할 작업을 저장하지 못했습니다. 저장 상태를 확인하세요.');
  for(const item of items){if(W.cancel||W.pauseRequested)break;activate(item.id);migrateReviews(item);const previous=structuredClone(item.payload),pendingIds=previous?reviewOverview(item).unresolved.map(r=>r.id):null;invalidateFeatureImage(item,'분석 중');const controller=new AbortController();S.controller=controller;item.running=true;queue();progress(true);$('workspaceStatus').textContent=(Object.keys(W.batch.done).length+1)+' / '+W.batch.ids.length+'장 검증 중';
   try{const targets=item.targets.filter(t=>t.text),payload=kind==='pending'&&previous?await reviewPending(item.file,previous,targets,controller.signal,pendingIds):await analyzeImage(item.file,targets,controller.signal,false);S.last=payload;S.targets=targets;S.resultUrl=URL.createObjectURL(item.file);item.problem='';await show(payload,targets,item.file);snapshot();W.batch.done[item.id]=batchSignature(item);completed++}
   catch(e){item.problem=e.name==='AbortError'?'취소됨':e.message;if(e.name==='AbortError')W.cancel=true;delete W.batch.done[item.id];queue()}
   finally{item.running=false;S.controller=null;progress(false)}
   dirty();if(!(await saveDraft(true))?.ok){checkpointError='결과 저장 실패 · 안전하게 일시정지했습니다.';break}
  }
 }catch(e){checkpointError=e.message;error(e.message)}finally{
  W.batch.status=checkpointError||W.cancel||W.pauseRequested||W.batch.ids.some(id=>{const item=W.items.find(i=>i.id===id);return item&&(!item.payload||W.batch.done[id]!==batchSignature(item))})?'paused':'complete';W.busy=false;unlock();dirty();await saveDraft();queue();$('workspaceStatus').textContent=checkpointError||(W.batch.status==='paused'?'일시정지 · 남은 이미지 이어서 검증을 사용할 수 있습니다.':'일괄 검증 완료 · 이미지별 결과가 임시 저장됐습니다.');refreshFeatures();
 }
}
`;
