export const languages=[["ko","한국어"],["en","영어"],["ja","일본어"],["zh-CN","중국어 간체"],["zh-TW","중국어 번체"],["de","독일어"],["fr","프랑스어"],["es","스페인어"],["neutral","언어 무관 (숫자·기호)"]].map(([id,label])=>({id,label}));
const allowed=new Set(["image/png","image/jpeg","image/webp"]),buckets=new Map(),headers={"x-content-type-options":"nosniff","referrer-policy":"no-referrer","permissions-policy":"camera=(self)","cross-origin-opener-policy":"same-origin"};
const ocrCache=new Map(),pendingOcr=new Map(),OCR_CACHE_MS=600000,OCR_CACHE_LIMIT=30;
const reply=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json;charset=utf-8","cache-control":"no-store",...headers,...extra}});
const nl=value=>String(value??"").replace(/\r\n?/g,"\n"),compact=value=>nl(value).replace(/\s+/gu,""),plain=value=>nl(value).replace(/[\s\p{P}\p{S}]+/gu,""),word=char=>/[\p{L}\p{N}_]/u.test(char||"");
const wrapClean=value=>nl(value).replace(/[ \t]*\n+[ \t]*/gu,"\n");
function wrappedBounded(h,n,fold=false){let H=wrapClean(h),N=wrapClean(n);if(fold){H=H.toLocaleLowerCase();N=N.toLocaleLowerCase()}for(let start=0;start<H.length;start++){const queue=[[start,0]],seen=new Set;for(let q=0;q<queue.length;q++){const[i,j]=queue[q],key=i+":"+j;if(seen.has(key))continue;seen.add(key);if(j===N.length){if((!word(N[0])||!word(H[start-1]))&&(!word(N[N.length-1])||!word(H[i])))return true;continue}if(i>=H.length)continue;const hc=H[i],nc=N[j];if(hc==="\n"){queue.push([i+1,j]);if(nc===" "||nc==="\n")queue.push([i+1,j+1])}if(nc==="\n"){queue.push([i,j+1]);if(hc===" "||hc==="\n")queue.push([i+1,j+1])}if(hc===nc&&hc!=="\n")queue.push([i+1,j+1])}}return false}

async function limited(req,env){
  const key=req.headers.get("cf-connecting-ip")||req.headers.get("x-forwarded-for")?.split(",")[0]||"anonymous",now=Date.now();
  if(env.DB)try{const start=Math.floor(now/60000)*60000,row=await env.DB.prepare(`INSERT INTO rate_limits (client_key,window_start,request_count,updated_at) VALUES (?,?,1,?) ON CONFLICT(client_key,window_start) DO UPDATE SET request_count=request_count+1,updated_at=excluded.updated_at RETURNING request_count`).bind(key,start,now).first();if(Math.random()<.02)env.DB.prepare("DELETE FROM rate_limits WHERE updated_at < ?").bind(now-3600000).run().catch(()=>{});return Number(row?.request_count||0)>20?Math.max(1,Math.ceil((start+60000-now)/1000)):0}catch(error){console.warn("Persistent rate limit unavailable; using local fallback",error)}
  const list=(buckets.get(key)||[]).filter(time=>now-time<60000);if(list.length>=20)return Math.max(1,Math.ceil((60000-(now-list[0]))/1000));list.push(now);buckets.set(key,list);return 0;
}
function magic(bytes){if(bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47)return"image/png";if(bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)return"image/jpeg";if(String.fromCharCode(...bytes.slice(0,4))==="RIFF"&&String.fromCharCode(...bytes.slice(8,12))==="WEBP")return"image/webp";return null}
function dimensions(bytes,type){if(type==="image/png"&&bytes.length>=24){const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);return{width:v.getUint32(16),height:v.getUint32(20)}}if(type==="image/jpeg"){for(let o=2;o+8<bytes.length;){if(bytes[o]!==255){o++;continue}const m=bytes[o+1],len=(bytes[o+2]<<8)+bytes[o+3];if([192,193,194,195,197,198,199,201,202,203,205,206,207].includes(m))return{height:(bytes[o+5]<<8)+bytes[o+6],width:(bytes[o+7]<<8)+bytes[o+8]};if(!len||len<2)break;o+=2+len}}if(type==="image/webp"&&String.fromCharCode(...bytes.slice(12,16))==="VP8X")return{width:1+bytes[24]+(bytes[25]<<8)+(bytes[26]<<16),height:1+bytes[27]+(bytes[28]<<8)+(bytes[29]<<16)};return null}
function region(value){if(!value)return null;const r={x:+value.x,y:+value.y,width:+value.width,height:+value.height};return Object.values(r).every(Number.isFinite)&&r.x>=0&&r.y>=0&&r.width>0&&r.height>0&&r.x+r.width<=1.001&&r.y+r.height<=1.001?r:null}
function targets(value){try{const known=new Set(languages.map(x=>x.id)),items=JSON.parse(value||"[]");if(!Array.isArray(items)||!items.length||items.length>80)return null;return items.map((x,i)=>{const area=region(x?.region),text=nl(x?.text),language=String(x?.language||"");if(!x||typeof x!=="object"||x.region!=null&&!area||!text.length||text.length>3000||!known.has(language))throw Error("invalid_target");return{id:String(x.id||`entry-${i+1}`).slice(0,80),label:String(x.label||"").slice(0,120),language,mode:x.mode==="required"?"required":"exact",text,region:area}})}catch{return null}}
function bounded(h,n){if(!n)return null;for(let p=0;p<=h.length-n.length;){const i=h.indexOf(n,p);if(i<0)return null;const a=h[i-1]||"",z=h[i+n.length]||"";if(!(word(n[0])&&word(a))&&!(word(n.at(-1))&&word(z)))return{i,value:h.slice(i,i+n.length)};p=i+1}return null}
function compactBounded(h,n,fold=false){h=nl(h);n=compact(n);let out="";const map=[];for(let i=0;i<h.length;i++)if(!/\s/u.test(h[i])){out+=h[i];map.push(i)}if(fold){out=out.toLocaleLowerCase();n=n.toLocaleLowerCase()}for(let p=0;p<=out.length-n.length;){const i=out.indexOf(n,p);if(i<0)return null;const a=h[map[i]-1]||"",z=h[map[i+n.length-1]+1]||"";if(!(word(n[0])&&word(a))&&!(word(n.at(-1))&&word(z)))return{i,value:out.slice(i,i+n.length)};p=i+1}return null}
function compare(h,n,mode){if(mode==="required"){if(compactBounded(h,n))return["matched","공백과 줄바꿈을 제외하고 모두 일치했습니다."];if(compactBounded(h,n,true))return["case_mismatch","대소문자가 다릅니다."]}else{const H=nl(h),N=nl(n);if(bounded(H,N))return["matched","정확히 일치했습니다."];if(wrappedBounded(h,n))return["matched","자동 줄바꿈을 제외하고 정확히 일치했습니다."];if(bounded(H.toLocaleLowerCase(),N.toLocaleLowerCase())||wrappedBounded(h,n,true))return["case_mismatch","대소문자가 다릅니다."];if(compactBounded(h,n))return["whitespace_mismatch","띄어쓰기가 다릅니다."]}if(plain(n)&&bounded(plain(h),plain(n)))return["symbol_mismatch","기호 또는 문장부호가 다릅니다."];return["missing","문구를 찾지 못했습니다."]}
function sanitizeLines(value){return(Array.isArray(value)?value:[]).slice(0,1200).map(x=>({text:nl(x?.text).replace(/\n+/g," ").trim(),confidence:Math.max(0,Math.min(1,+x?.confidence||0)),boundingBox:region(x?.boundingBox)})).filter(x=>x.text)}
function overlap(line,target){if(!target)return 1;const b=line.boundingBox;if(!b)return 0;const w=Math.max(0,Math.min(b.x+b.width,target.x+target.width)-Math.max(b.x,target.x)),h=Math.max(0,Math.min(b.y+b.height,target.y+target.height)-Math.max(b.y,target.y)),area=b.width*b.height;return area?w*h/area:0}
function distance(a,b){a=compact(a);b=compact(b);if(!a)return b.length;if(!b)return a.length;const row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let diagonal=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const saved=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,diagonal+(a[i-1]===b[j-1]?0:1));diagonal=saved}}return row[b.length]}
function closest(lines,text){return lines.reduce((best,line)=>{const score=distance(line.text,text)/Math.max(1,compact(line.text).length,compact(text).length);return!best||score<best.score?{line,score}:best},null)}
function adjacent(a,b){const x=a.boundingBox,y=b.boundingBox;if(!x||!y)return !x&&!y;const height=Math.max(x.height,y.height),gap=y.y-(x.y+x.height),shared=Math.max(0,Math.min(x.x+x.width,y.x+y.width)-Math.max(x.x,y.x));return gap>=-height*.35&&gap<=height*1.8&&(shared>0||Math.abs(x.x-y.x)<=.08)}
function candidates(lines,fallback){if(!lines.length)return fallback?[{text:fallback,lines:[]}]:[];const out=[];for(let i=0;i<lines.length;i++){let group=[];for(let j=i;j<Math.min(lines.length,i+8);j++){if(j>i&&!adjacent(lines[j-1],lines[j]))break;group.push(lines[j]);out.push({text:group.map(x=>x.text).join("\n"),lines:[...group]})}}return out}
function findMatch(groups,text,mode){let near=null;const rank={case_mismatch:3,whitespace_mismatch:2,symbol_mismatch:1,missing:0};for(const group of [...groups].sort((a,b)=>a.lines.length-b.lines.length)){const[code,message]=compare(group.text,text,mode);if(code==="matched")return{code,message,group};if(!near||rank[code]>rank[near.code])near={code,message,group}}return near||{code:"missing",message:"문구를 찾지 못했습니다.",group:null}}
function validate(target,all,fallback){const scoped=all.filter(line=>overlap(line,target.region)>=.35),groups=candidates(scoped,target.region?"":fallback),parts=target.mode==="required"?target.text.split("\n").map(x=>x.trim()).filter(Boolean):[target.text],checks=parts.map(candidate=>({candidate,...findMatch(groups,candidate,target.mode)})),found=checks.length>0&&checks.every(x=>x.code==="matched"),matchedLines=found?[...new Set(checks.flatMap(x=>x.group?.lines||[]))]:[],evidence=matchedLines.filter(x=>x.boundingBox).slice(0,12),bad=checks.filter(x=>x.code!=="matched"),nearest=found?null:closest(scoped.length?scoped:all,bad[0]?.candidate||target.text),nearestEvidence=nearest?.line?.boundingBox?[nearest.line]:[],confidenceLines=evidence.length?evidence:nearestEvidence,confidence=confidenceLines.length?confidenceLines.reduce((sum,x)=>sum+x.confidence,0)/confidenceLines.length:0;return{...target,found,recognitionScores:matchedLines.map(x=>x.confidence),matchedText:found?target.text:"",observedText:nearest?.line?.text||"",confidence,reasonCode:found?"matched":bad[0]?.code||"missing",reason:found?"일치하는 문구를 찾았습니다.":bad[0]?.message||"문구를 찾지 못했습니다.",missingCandidates:bad.map(x=>x.candidate),evidence,nearestEvidence,overlapThreshold:target.region ? .35 : null}}

export {magic,dimensions,targets,sanitizeLines,validate};

