export const uxClient=String.raw`
var UX={ready:false,edits:new Map(),notes:new Map(),filter:'all',viewImage:null,zoomMode:'fit',compareZoom:1};
function needsAttention(item){return !!(item.problem||!item.payload?.result?.results?.length||reviewOverview(item).unresolved.length)}
function editState(){return {targets:[...$('entries').children].map(read),ignoreRegions:structuredClone(activeItem()?.ignoreRegions||[])}}
function editHistory(){const key=W.draftId+':'+W.active;if(!UX.edits.has(key))UX.edits.set(key,{undo:[],redo:[]});return UX.edits.get(key)}
function rememberEdit(){if(!UX.ready||featureBusy()||!activeItem())return;editCheckpoint(editHistory(),editState());refreshEditButtons()}
function restoreEdit(direction){if(featureBusy()||!activeItem())return;const state=editStep(editHistory(),editState(),direction);if(!state)return;const item=activeItem();item.ignoreRegions=state.ignoreRegions;resetResult();$('entries').replaceChildren();S.n=0;(state.targets.length?state.targets:[{}]).forEach(add);item.targets=state.targets;item.payload=null;item.resultTargets=[];item.problem='편집 되돌림 · 재검증 필요';dirty();queue();setWorkbenchTab('settings');refreshEditButtons()}
function refreshEditButtons(){if(!UX.ready)return;const history=editHistory();$('undoEdit').disabled=featureBusy()||!history.undo.length;$('redoEdit').disabled=featureBusy()||!history.redo.length}
function fitViewport(){const p=$('preview'),v=$('canvasViewport');UX.zoomMode='fit';setZoom(fitScale(p.naturalWidth,p.naturalHeight,v.clientWidth,v.clientHeight),true);v.scrollTo(0,0)}
function refreshReviewSummary(){const item=activeItem();if(!item||!S.last)return;const summary=reviewOverview(item),auto=summary.automaticPass===summary.total,root=$('summary');root.className='summary '+(summary.issues?'fail':summary.unresolved.length?'review':'pass');root.innerHTML='<strong>'+(summary.issues?'수동 검수에서 문제가 표시되었습니다.':summary.unresolved.length?'확인할 문구가 남아 있습니다.':summary.accepted?'검수 결과를 확인했습니다.':'자동 검증이 완료되었습니다.')+'</strong><div class="judgment-row"><span class="verdict '+(auto?'good':'warn')+'">자동: '+summary.automaticPass+' / '+summary.total+' 통과</span><span class="verdict '+(summary.issues?'bad':'neutral')+'">수동: 확인 '+summary.accepted+' · 문제 '+summary.issues+' · 미검수 '+summary.unreviewed+'</span></div><span>미해결 '+summary.unresolved.length+'개'+(S.last.result.timing?.totalMs?' · 분석 '+(S.last.result.timing.totalMs/1000).toFixed(1)+'초':'')+'</span><span class="analysis-detail">'+esc(analysisDetails(S.last.result))+'</span>';} 
function reviewDetail(){if(!UX.ready)return;const item=activeItem(),result=S.last?.result?.results?.find(r=>r.id===S.selectedResult),root=$('reviewDetailBody');$('manualReviewPanel').hidden=UI.tab!=='results'||!result;refreshReviewSummary();refreshEditButtons();if(!result){if(UX.reviewAdvanced)$('manualReviewPanel').append(UX.reviewAdvanced);root.replaceChildren();return}const key=W.active+':'+result.id,record=item.reviews?.[result.id],current=manualState(item,result.id),old=$('reviewNote');if(old&&old.dataset.key===key&&document.activeElement===old){refreshDetailState(current);return}const note=item.reviewNotes?.[result.id]?.note??(UX.notes.has(key)?UX.notes.get(key):record?.note||'');
 root.innerHTML='<div class="detail-heading"><h3>'+esc(result.label||'선택 문구')+'</h3><button id="nextReview" class="ghost small">다음 미해결 →</button></div><div class="judgment-row"><span class="verdict '+(result.found?'good':result.reviewRequired?'warn':'bad')+'">자동: '+(result.found?'✓ 통과':result.reviewRequired?'! 확인 필요':'× 미통과')+'</span><span id="humanVerdict" class="verdict neutral"></span></div><div class="review-scroll"><div class="text-comparison"><label>기대 문구<pre>'+esc(result.text)+'</pre></label><label>OCR 결과<pre>'+esc(result.observedText||result.matchedText||'인식된 문구 없음')+'</pre></label></div>'+(!result.found?diffHtml(result.text,result.observedText):'')+'<p class="help">'+esc(result.reason||'')+(record&&!current?' · 결과 변경으로 재검수 필요':'')+'</p><label for="reviewNote">검수 메모</label><textarea id="reviewNote" maxlength="2000" rows="1" placeholder="확인한 내용이나 수정할 점"></textarea></div><div class="review-buttons"><button id="acceptNext" class="small">확인 완료 후 다음 →</button><button id="acceptReview" class="secondary small">확인 완료</button><button id="issueReview" class="danger small">문제 있음</button><button id="clearReview" class="ghost small">기록 지우기</button></div>';
 if(UX.reviewAdvanced)root.querySelector('.review-scroll').append(UX.reviewAdvanced);$('reviewNote').value=note;$('reviewNote').dataset.key=key;$('reviewNote').oninput=()=>saveNote(item,result.id,$('reviewNote').value);
 $('acceptReview').onclick=()=>saveManualReview('accepted');$('issueReview').onclick=()=>saveManualReview('issue');$('acceptNext').onclick=async()=>{if(await saveManualReview('accepted'))await nextReviewTarget(true)};$('nextReview').onclick=()=>nextReviewTarget();$('clearReview').onclick=()=>{if(featureBusy())return;delete item.reviews[result.id];delete item.reviewNotes?.[result.id];UX.notes.delete(key);dirty();queue();reviewDetail()};refreshDetailState(current);
}
function refreshDetailState(current){if(!$('humanVerdict'))return;const verdict=current?.verdict;$('humanVerdict').textContent='수동: '+(verdict==='accepted'?'✓ 확인 완료':verdict==='issue'?'! 문제 있음':'미검수');$('humanVerdict').className='verdict '+(verdict==='issue'?'bad':verdict==='accepted'?'good':'neutral');for(const id of ['acceptReview','issueReview','acceptNext','clearReview','nextReview','reviewNote'])$(id).disabled=featureBusy();}
async function nextReviewTarget(includeUnreviewed=false){if(featureBusy())return;snapshot();const item=activeItem(),rows=item?.payload?.result?.results||[],start=rows.findIndex(r=>r.id===S.selectedResult),unresolved=new Set(reviewOverview(item).unresolved.map(r=>r.id));if(includeUnreviewed&&!unresolved.size)for(const r of rows)if(!manualState(item,r.id))unresolved.add(r.id);for(let n=1;n<=rows.length;n++){const r=rows[(start+n)%rows.length];if(unresolved.has(r.id)&&r.id!==S.selectedResult){selectReviewTarget(r.id);return}}const index=W.items.indexOf(item);for(let n=1;n<W.items.length;n++){const next=W.items[(index+n)%W.items.length];if(needsAttention(next)||includeUnreviewed&&reviewOverview(next).unreviewed){activate(next.id);setWorkbenchTab(next.payload?'results':'settings');const r=reviewOverview(next).unresolved[0]||(includeUnreviewed?next.payload?.result?.results?.find(r=>!manualState(next,r.id)):null);if(r)selectReviewTarget(r.id);return}}$('workspaceStatus').textContent=unresolved.size?'현재 문구에 문제가 남아 있습니다.':'미해결 검수 항목이 없습니다.';}
function selectReviewTarget(id){const filter=UX.filter,rows=S.last.result.results,r=rows.find(r=>r.id===id);if(!r)return;const visible=resultMatches(r,activeItem(),filter,UX.search||'');if(!visible){UX.filter='all';UX.search='';if($('resultSearch'))$('resultSearch').value='';document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter==='all'))}S.selectedResult=id;render(UX.filter);evidence(id,true);$('results').querySelector('[data-id="'+CSS.escape(id)+'"]')?.scrollIntoView({block:'nearest'})}
function batchCandidates(kind){if(kind==='resume')return W.batch?.ids.map(id=>W.items.find(i=>i.id===id)).filter(i=>i&&(!i.payload||W.batch.done[i.id]!==batchSignature(i)))||[];return W.items.filter(i=>kind==='selected'?i.selected:kind==='pending'?needsAttention(i):true)}
function prepareBatch(kind){if(featureBusy())return;snapshot();const state=batchReadiness(batchCandidates(kind));$('batchReadyInfo').textContent='준비 '+state.ready.length+'장 / 문구 없음 '+state.missing.length+'장';$('batchMissingList').innerHTML=state.missing.map(i=>'<button class="ghost small" data-missing="'+i.id+'">'+esc(i.file.name)+' · 문구 입력 →</button>').join('');$('batchMissingList').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('batchReadyDialog').close();activate(b.dataset.missing);setWorkbenchTab('settings')});$('startReadyBatch').textContent='준비된 '+state.ready.length+'장 검증';$('startReadyBatch').disabled=!state.ready.length;$('startReadyBatch').onclick=()=>{$('batchReadyDialog').close();runBatch(kind,{skipMissing:true})};$('batchReadyDialog').showModal()}
function refreshUx(){if(!UX.ready)return;refreshEditButtons();const state=batchReadiness(W.items);$('batchReadiness').textContent='준비 '+state.ready.length+'장 · 문구 없음 '+state.missing.length+'장';$('nextAttention').disabled=featureBusy()||!W.items.some(needsAttention);$('batchReadiness').disabled=featureBusy()||!W.items.length;refreshReviewSummary();}
function setLayoutMode(mode){document.body.dataset.layout=mode;document.querySelectorAll('[data-layout-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.layoutMode===mode)));try{localStorage.setItem('language-test-layout',mode)}catch{}requestAnimationFrame(()=>{if(UX.zoomMode==='fit')fitViewport()})}
function panelResize(handle,side){handle.onpointerdown=event=>{if(event.button!==0)return;event.preventDefault();handle.setPointerCapture(event.pointerId);const start=event.clientX,shell=document.querySelector('.workbench-shell'),panel=side==='left'?document.querySelector('.workspace-card'):document.querySelector('.workbench-right'),width=panel.getBoundingClientRect().width;handle.onpointermove=e=>{const available=Math.max(200,shell.clientWidth-420),size=Math.max(side==='left'?180:300,Math.min(side==='left'?380:620,available,width+(e.clientX-start)*(side==='left'?1:-1)));shell.style.setProperty('--'+side+'-width',size+'px')};handle.onpointerup=()=>{handle.onpointermove=null;try{localStorage.setItem('language-test-'+side+'-width',shell.style.getPropertyValue('--'+side+'-width'))}catch{}if(UX.zoomMode==='fit')fitViewport()};handle.onpointercancel=()=>handle.onpointermove=null};handle.onkeydown=e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const panel=side==='left'?document.querySelector('.workspace-card'):document.querySelector('.workbench-right'),delta=(e.key==='ArrowRight'?20:-20)*(side==='left'?1:-1);document.querySelector('.workbench-shell').style.setProperty('--'+side+'-width',Math.max(side==='left'?180:300,Math.min(side==='left'?380:620,panel.clientWidth+delta))+'px');if(UX.zoomMode==='fit')fitViewport()};}
function compareView(zoom,anchor=null){const canvases=['baselineCanvas','currentCanvas','diffCanvas'].map($),v=$('currentCanvas').parentElement;if(!canvases[0].width)return;const old=UX.compareZoom;UX.compareZoom=Math.max(.05,Math.min(8,zoom));for(const c of canvases){const box=c.parentElement,x=anchor?.x??box.clientWidth/2,y=anchor?.y??box.clientHeight/2,left=(box.scrollLeft+x)/old*UX.compareZoom-x,top=(box.scrollTop+y)/old*UX.compareZoom-y;c.style.width=c.width*UX.compareZoom+'px';c.style.height=c.height*UX.compareZoom+'px';box.scrollLeft=left;box.scrollTop=top}$('compareZoomLabel').textContent=Math.round(UX.compareZoom*100)+'%';}
function fitComparison(){const c=$('compareDisplay')?.value==='diff'?$('currentCanvas'):$('diffCanvas'),v=c.parentElement;compareView(fitScale(c.width,c.height,v.clientWidth,v.clientHeight));for(const id of ['baselineCanvas','currentCanvas','diffCanvas'])$(id).parentElement.scrollTo(0,0)}
function mountUx(){
 const shell=document.querySelector('.workbench-shell');shell.style.setProperty('--left-width','238px');shell.style.setProperty('--right-width','390px');for(const side of ['left','right']){const grip=document.createElement('div');grip.className='panel-grip '+side;grip.tabIndex=0;grip.setAttribute('role','separator');grip.setAttribute('aria-orientation','vertical');grip.setAttribute('aria-label',(side==='left'?'이미지 목록':'문구 패널')+' 너비 조절');shell.append(grip);panelResize(grip,side);try{const width=parseInt(localStorage.getItem('language-test-'+side+'-width'));if(Number.isFinite(width))shell.style.setProperty('--'+side+'-width',Math.max(side==='left'?180:300,Math.min(side==='left'?380:620,width))+'px')}catch{}}
 const view=document.createElement('div');view.className='layout-switch';view.innerHTML='<button class="ghost small" data-layout-mode="standard">기본</button><button class="ghost small" data-layout-mode="image">이미지 집중</button><button class="ghost small" data-layout-mode="text">문구 집중</button>';document.querySelector('.preview-card>.head').append(view);view.querySelectorAll('button').forEach(b=>b.onclick=()=>setLayoutMode(b.dataset.layoutMode));
 const zoom=document.createElement('button');zoom.id='originalImage';zoom.className='tool-button text';zoom.textContent='원본 100%';$('fitImage').after(zoom);zoom.onclick=()=>{UX.zoomMode='original';setZoom(1,true)};$('fitImage').onclick=fitViewport;$('zoomOut').onclick=()=>setZoom(S.zoom/1.2);$('zoomIn').onclick=()=>setZoom(S.zoom*1.2);
 const edits=document.createElement('div');edits.className='edit-tools';edits.innerHTML='<button id="undoEdit" class="tool-button" title="문구·영역 실행 취소 (Ctrl+Z)">↶ 실행 취소</button><button id="redoEdit" class="tool-button" title="다시 실행 (Ctrl+Shift+Z)">↷ 다시 실행</button>';document.querySelector('.canvas-toolbar').append(edits);$('undoEdit').onclick=()=>restoreEdit('undo');$('redoEdit').onclick=()=>restoreEdit('redo');
 $('entries').addEventListener('click',event=>{if(event.target.closest('.remove,.duplicate,.clear-region,.apply-region'))rememberEdit()},true);for(const id of ['clearEntries','removeDuplicates','addEntry','addDraftTargets'])$(id).addEventListener('click',rememberEdit,true);
 document.addEventListener('keydown',event=>{if(document.querySelector('dialog[open]')||event.target.closest('input,textarea,[contenteditable=true]'))return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();restoreEdit(event.shiftKey?'redo':'undo')}});
 const panel=$('manualReviewPanel');panel.classList.add('review-detail');panel.innerHTML='<div id="reviewDetailBody"></div><details class="review-advanced"><summary>선택 영역 재확인</summary><div id="reviewRegionTools"></div></details>';document.querySelector('.workbench-right').insertBefore(panel,document.querySelector('.workbench-right .runbar'));for(const id of ['regionProvider','verifyRegionAi','retryRegion'])$('reviewRegionTools').append($(id));panel.hidden=true;UX.reviewAdvanced=panel.querySelector('.review-advanced');
 const ready=document.createElement('button');ready.id='batchReadiness';ready.className='ghost small';document.querySelector('.batch-more').before(ready);ready.onclick=()=>prepareBatch('all');featureDialog('batchReadyDialog','일괄 검증 준비','<p id="batchReadyInfo"></p><p class="help">문구가 없는 이미지는 목록에서 설정한 뒤 검증할 수 있습니다. 시작하면 준비된 이미지만 실행합니다.</p><div id="batchMissingList"></div><button id="startReadyBatch">준비된 이미지 검증</button>');$('runAll').onclick=()=>prepareBatch('all');$('runPending').onclick=()=>prepareBatch('pending');$('runSelected').onclick=()=>prepareBatch('selected');
 $('nextAttention').onclick=()=>{if(featureBusy())return;const start=W.items.findIndex(i=>i.id===W.active);for(let n=1;n<=W.items.length;n++){const item=W.items[(start+n)%W.items.length];if(needsAttention(item)){activate(item.id);setWorkbenchTab(item.payload?'results':'settings');return}}};
 const compareControls=document.createElement('div');compareControls.className='toolbar compare-tools';compareControls.innerHTML='<label>비교 범위<select id="compareScope"><option value="full">전체 화면 · 최대 1600px</option><option value="region">선택 영역 · 원본 해상도</option></select></label><button id="compareFit" class="ghost small">화면 맞춤</button><button id="compareOriginal" class="ghost small">비교 픽셀 100%</button><button id="compareOut" class="ghost small" aria-label="비교 축소">−</button><output id="compareZoomLabel">100%</output><button id="compareIn" class="ghost small" aria-label="비교 확대">+</button>';document.querySelector('.compare-images').before(compareControls);$('compareScope').onchange=resetComparisonView;$('compareFit').onclick=fitComparison;$('compareOriginal').onclick=()=>compareView(1);$('compareOut').onclick=()=>compareView(UX.compareZoom/1.2);$('compareIn').onclick=()=>compareView(UX.compareZoom*1.2);
 for(const id of ['baselineCanvas','currentCanvas','diffCanvas']){const canvas=$(id),v=document.createElement('div');v.className='comparison-viewport';canvas.before(v);v.append(canvas);let drag=null;v.onscroll=()=>{for(const other of document.querySelectorAll('.comparison-viewport'))if(other!==v&&(Math.abs(other.scrollLeft-v.scrollLeft)>1||Math.abs(other.scrollTop-v.scrollTop)>1)){other.scrollLeft=v.scrollLeft;other.scrollTop=v.scrollTop}};v.onpointerdown=e=>{if(e.button!==0)return;drag={x:e.clientX,y:e.clientY,left:v.scrollLeft,top:v.scrollTop};v.setPointerCapture(e.pointerId);e.preventDefault()};v.onpointermove=e=>{if(drag){v.scrollLeft=drag.left-e.clientX+drag.x;v.scrollTop=drag.top-e.clientY+drag.y}};v.onpointerup=v.onpointercancel=()=>drag=null;v.onwheel=e=>{if(!e.ctrlKey)return;e.preventDefault();const rect=v.getBoundingClientRect();compareView(UX.compareZoom*(e.deltaY<0?1.2:1/1.2),{x:e.clientX-rect.left,y:e.clientY-rect.top})};}
 const more=document.createElement('details');more.className='workspace-more';more.innerHTML='<summary>작업 도구 더보기</summary>';const actions=document.querySelector('.feature-actions');actions.before(more);more.append(actions);
 const resultMore=document.createElement('details');resultMore.className='result-more';resultMore.innerHTML='<summary aria-label="결과 도구 더보기" title="내보내기·이미지 새로 읽기">⋯</summary>';const exports=document.querySelector('.export-group');exports.before(resultMore);resultMore.append(exports);
 UX.ready=true;let layout='standard';try{layout=localStorage.getItem('language-test-layout')||layout}catch{}setLayoutMode(['standard','image','text'].includes(layout)?layout:'standard');new ResizeObserver(()=>{if(UX.zoomMode==='fit'&&$('preview').naturalWidth)fitViewport()}).observe($('canvasViewport'));refreshUx();
}
`;
