// Embedded inside the client closure to share the existing image and result controls.
export const workspaceClient=String.raw`
const W={projectId:null,items:[],active:null,busy:false,operation:false,cancel:false,dirty:false};
function snapshot(){if(typeof captureImageView==='function')captureImageView();const item=W.items.find(x=>x.id===W.active);if(item){item.targets=[...document.querySelectorAll('.entry')].map(read);item.payload=S.last;item.resultTargets=S.targets}}
function dirty(){W.dirty=true;W.revision++;scheduleDraft();$('draftStatus').textContent='변경 사항 임시 저장 중…';$('workspaceStatus').textContent='저장하지 않은 변경 사항';refreshWorkbench()}
function edited(){const item=W.items.find(x=>x.id===W.active),current=[...document.querySelectorAll('.entry')].map(read);if(S.last&&targetSignature(current)!==targetSignature(S.targets)){resetResult();if(item){item.payload=null;item.resultTargets=[];item.problem='설정 변경 · 재검증 필요'}queue()}dirty()}
function lockWorkspace(){stopRegion();W.operation=true;const controls=['compareScope','compareDisplay','compareBlend','baselineFiles','baselineTag','runCompare','autoAlign','diffThreshold','diffX','diffY','diffScale','profileInclude','ocrLayout','chooseFile','takePhoto','imageInput','workspaceFile','saveLocal','saveWorkspace','openWorkspace','newWorkspace','workspaceName','workspaceFolder','cloudProject','analysisMode','runAll','run','retry','retryRegion','addEntry','clearEntries','removeDuplicates','importExcel','selectImages','copySettings','runSelected','runPending','regionProvider','verifyRegionAi','clearOcrCache','folderFilter','applyFolderMove','projectSearch','projectStatus','savePreset','loadPreset','deletePreset','presetName','presetSelect','undoImage','applyCopy','copyMode','chooseFolder','autoReview','autoReviewProvider'];const state=controls.map(id=>[$(id),$(id).disabled]);const inert=['entries','imageQueue','projectLibrary','folderTools','recoveryList','trashList'].map(id=>[$(id),$(id).inert]);state.forEach(([el])=>el.disabled=true);inert.forEach(([el])=>el.inert=true);refreshWorkbench();let released=false;return()=>{if(released)return;released=true;state.forEach(([el,disabled])=>el.disabled=disabled);inert.forEach(([el,value])=>el.inert=value);W.operation=false;W.sortable?.option('disabled',false);$('verifyRegionAi').disabled=!selectedArea(S.last?.result?.results?.find(x=>x.id===S.selectedResult));refreshWorkbench()}}

function queue(){
  W.sortable?.destroy();
  $('imageQueue').innerHTML=W.items.map((item,i)=>'<div class="queue-item" data-item="'+item.id+'"><input type="checkbox" class="queue-check" data-check="'+item.id+'" aria-label="'+esc(item.file.name)+' 선택"'+(item.selected?' checked':'')+'><span class="queue-handle" title="드래그하여 순서 변경">≡</span><button type="button" class="ghost image-tab '+(item.id===W.active?'active':'')+'" data-image="'+item.id+'"><img loading="lazy" decoding="async" class="queue-thumb" alt="" src="'+(item.thumb||(item.thumb=URL.createObjectURL(item.file)))+'">'+(i+1)+'. '+esc(item.file.name)+' <small>'+esc(item.running?'분석 중…':item.problem||(item.payload?item.payload.result.foundCount+'/'+item.payload.result.totalCount+' 통과':'검증 전'))+'</small></button><button type="button" class="ghost small" data-shift="'+item.id+'" data-offset="-1" aria-label="'+esc(item.file.name)+' 앞으로">↑</button><button type="button" class="ghost small" data-shift="'+item.id+'" data-offset="1" aria-label="'+esc(item.file.name)+' 뒤로">↓</button><button type="button" class="ghost remove-image" data-remove="'+item.id+'" aria-label="'+esc(item.file.name)+' 삭제">×</button></div>').join('');
  $('imageCount').textContent=W.items.length+' / 200장';selectionCount();
  $('imageQueue').querySelectorAll('[data-image]').forEach(b=>b.onclick=()=>{if(!W.busy&&!W.operation&&!S.controller)activate(b.dataset.image)});
  $('imageQueue').querySelectorAll('[data-check]').forEach(b=>b.onchange=()=>{if(W.busy||W.operation||S.controller){b.checked=!!W.items.find(x=>x.id===b.dataset.check)?.selected;return}W.items.find(x=>x.id===b.dataset.check).selected=b.checked;selectionCount()});
  $('imageQueue').querySelectorAll('[data-shift]').forEach(b=>b.onclick=()=>{if(W.busy||W.operation||S.controller)return;snapshot();const from=W.items.findIndex(x=>x.id===b.dataset.shift),to=from+Number(b.dataset.offset);if(to<0||to>=W.items.length)return;W.items.splice(to,0,W.items.splice(from,1)[0]);dirty();queue()});
  $('imageQueue').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(W.busy||W.operation||S.controller)return;snapshot();W.items=W.items.filter(x=>{if(x.id===b.dataset.remove){W.removed.push({item:x,index:W.items.indexOf(x)});if(W.removed.length>10){const dropped=W.removed.shift();if(dropped.item.thumb)URL.revokeObjectURL(dropped.item.thumb)}$('undoImage').disabled=false;return false}return true});if(W.active===b.dataset.remove){W.active=null;if(W.items.length)activate(W.items[0].id);else{resetResult();$('imageInput').value='';$('previewShell').classList.add('hidden');$('statusFile').textContent='이미지 대기'}}dirty();queue()});
  if(typeof Sortable!=='undefined')W.sortable=Sortable.create($('imageQueue'),{animation:150,forceFallback:true,fallbackTolerance:3,handle:'.queue-handle',draggable:'.queue-item',disabled:!!(W.busy||W.operation||S.controller),onMove:()=>!(W.busy||W.operation||S.controller),onEnd:()=>{if(W.busy||W.operation||S.controller){queue();return}snapshot();const items=new Map(W.items.map(x=>[x.id,x]));W.items=[...$('imageQueue').children].map(row=>items.get(row.dataset.item));dirty();queue()}});
  refreshWorkbench();
}
function selectionCount(){$('selectionCount').textContent=W.items.filter(x=>x.selected).length+'장 선택';refreshWorkbench()}
$('selectImages').onclick=()=>{if(W.busy||W.operation||S.controller)return;const value=!W.items.every(x=>x.selected);W.items.forEach(x=>x.selected=value);queue()};
$('copySettings').onclick=()=>{
  if(W.busy||W.operation||S.controller)return;snapshot();
  const source=W.items.find(x=>x.id===W.active),dest=W.items.filter(x=>x.selected&&x!==source);
  if(!source||!dest.length)return error('설정을 복사할 다른 이미지를 선택하세요.');
  dest.forEach(item=>{item.targets=source.targets.map(t=>({...structuredClone(t),id:crypto.randomUUID()}));item.payload=null;item.resultTargets=[];item.problem='설정 복사 · 재검증 필요'});
  dirty();queue();$('workspaceStatus').textContent=dest.length+'장에 문구·언어·영역을 복사했습니다 · 저장하세요.';
};

function activate(id){captureImageView();snapshot();const item=W.items.find(x=>x.id===id);if(!item)return;migrateReviews(item);if(typeof UX!=='undefined'&&UX.regionSelection)UX.regionSelection.clear();stopRegion();cancelIgnore();W.active=id;image(item.file);$('entries').replaceChildren();S.n=0;(item.targets.length?item.targets:[{}]).forEach(add);if(item.payload){S.last=item.payload;S.targets=item.resultTargets||item.targets;S.resultUrl=URL.createObjectURL(item.file);show(item.payload,S.targets,item.file,false)}queue()}
async function addImages(files){const incoming=[...files],current=W.items.find(x=>x.id===W.active),transfer=new DataTransfer();if(current)transfer.items.add(current.file);$('imageInput').files=transfer.files;if(W.busy||W.operation||S.controller)return error('진행 중인 작업이 끝난 뒤 이미지를 추가하세요.');snapshot();if(W.items.length+incoming.length>200)return error('작업 하나에 최대 200장까지 추가할 수 있습니다.');if(W.items.reduce((n,x)=>n+x.file.size,0)+incoming.reduce((n,x)=>n+x.size,0)>512*1024*1024)return error('이미지 합계는 512MB 이하로 선택하세요.');const unlock=lockWorkspace();try{for(const file of incoming){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10485760)throw Error('PNG, JPG, WebP 형식의 10MB 이하 이미지를 선택하세요.');const bitmap=await createImageBitmap(file);const valid=bitmap.width*bitmap.height<=64000000;bitmap.close();if(!valid)throw Error('이미지 해상도가 너무 큽니다.')}const template=W.items.length?null:[...document.querySelectorAll('.entry')].map(read);const added=incoming.map(file=>({id:crypto.randomUUID(),file,targets:template?structuredClone(template):[],payload:null,resultTargets:[],ignoreRegions:[],reviews:{}}));W.items.push(...added);if(added.length)activate(added[0].id);dirty();queue();return true}catch(e){error(e.message)}finally{unlock()}}
const encodedFiles=new WeakMap();const encodeFile=file=>{if(encodedFiles.has(file))return encodedFiles.get(file);const task=new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>{encodedFiles.delete(file);reject(Error('이미지를 저장하지 못했습니다.'))};reader.readAsDataURL(file)});encodedFiles.set(file,task);return task};
$('saveWorkspace').onclick=async()=>{if(W.busy||W.operation||S.controller)return error('분석이 끝난 뒤 저장하세요.');snapshot();if(!W.items.length)return error('저장할 이미지를 추가하세요.');const unlock=lockWorkspace();try{const items=await Promise.all(W.items.map(async item=>({...(await storedItem(item,true))})));download(($('workspaceName').value.trim()||'Language Test 작업')+'.language-test.json',JSON.stringify({format:'language-test-workspace',version:1,name:$('workspaceName').value,folder:$('workspaceFolder').value,items,batch:W.batch||null,watchPath:$('watchPath').value}),'application/json');$('workspaceStatus').textContent='백업 파일 저장 요청 완료 · 다운로드 폴더에서 확인하세요.'}catch(e){error(e.message)}finally{unlock()}};
$('openWorkspace').onclick=()=>{if(W.busy||W.operation||S.controller)return error('분석이 끝나거나 취소한 뒤 불러오세요.');if(W.dirty&&!confirm('저장하지 않은 변경 사항이 있습니다. 다른 작업을 불러올까요?'))return;$('workspaceFile').click()};
$('workspaceFile').onchange=async event=>{const file=event.target.files[0];event.target.value='';if(file)await loadWorkspace(file)};
async function loadWorkspace(file,local=false){if(W.busy||W.operation||S.controller)return;await stopWatch();await saveDraft();const unlock=lockWorkspace();try{if(file.size>750*1024*1024)throw Error('작업 파일은 750MB 이하여야 합니다.');const data=validateWorkspace(JSON.parse(await file.text()));let total=0;const items=[];for(const item of data.items){const source=item.image?imageRefUrl(item.image):item.data;const response=await fetch(source);if(!response.ok)throw Error('원본 이미지를 읽지 못했습니다.');const blob=await response.blob();total+=blob.size;if(blob.size>10485760||total>512*1024*1024)throw Error('저장된 이미지 용량이 너무 큽니다.');const bitmap=await createImageBitmap(blob);const valid=bitmap.width*bitmap.height<=64000000;bitmap.close();if(!valid)throw Error('이미지 해상도가 너무 큽니다.');for(const historical of item.baselineHistory||[])if(historical.data){const response=await fetch(historical.data),blob=await response.blob();historical.image=await imageReference(blob);delete historical.data}if(item.baseline?.data){const response=await fetch(item.baseline.data),blob=await response.blob();item.baseline.image=await imageReference(blob);delete item.baseline.data}const loadedImageRef=item.image||await imageReference(blob);const resultTargets=Array.isArray(item.resultTargets)?item.resultTargets:item.targets,stale=item.payload&&targetSignature(item.targets)!==targetSignature(resultTargets);items.push({id:item.id||crypto.randomUUID(),file:new File([blob],item.name,{type:blob.type,lastModified:item.lastModified||0}),imageRef:loadedImageRef,targets:item.targets,payload:stale?null:item.payload,resultTargets,ignoreRegions:item.ignoreRegions||[],reviews:item.reviews||{},reviewNotes:item.reviewNotes||{},view:item.view||null,baselineHistory:item.baselineHistory||[],baseline:item.baseline||null,comparison:item.comparison||null,problem:stale?'설정 변경 · 재검증 필요':item.problem||''})}W.projectId=local?data.id:null;$('workspaceFolder').value=String(data.folder||'기본 폴더');W.items.forEach(x=>x.thumb&&URL.revokeObjectURL(x.thumb));W.removed.forEach(x=>x.item.thumb&&URL.revokeObjectURL(x.item.thumb));W.removed=[];$('undoImage').disabled=true;W.active=null;W.items=items;W.batch=data.batch?{...data.batch,status:data.batch.status==='complete'?'complete':'paused'}:null;$('watchPath').value=data.watchPath||'';$('workspaceName').value=String(data.name||'불러온 작업').slice(0,100);W.draftId=local==='draft'?data.id:crypto.randomUUID();W.projectId=local==='draft'?data.sourceProjectId||null:local===true?data.id:null;resetComparisonView();F.excelPlan=null;F.mapUndo=null;activate(items[0].id);W.dirty=local==='draft';if(W.dirty)dirty();$('workspaceStatus').textContent='저장된 이미지·문구·영역·결과를 불러왔습니다.';error('');if(UI?.ready)$('workbenchLibrary').close()}catch(e){error('작업을 불러오지 못했습니다: '+e.message)}finally{unlock()}};

$('runAll').onclick=()=>runBatch();$('runSelected').onclick=()=>runBatch('selected');$('runPending').onclick=()=>runBatch('pending');

$('cancelRun').onclick=()=>{W.cancel=true;S.controller?.abort()};
$('entries').addEventListener('input',edited);$('entries').addEventListener('change',edited);$('entries').addEventListener('click',event=>{if(event.target.closest('.remove,.duplicate,.clear-region,.apply-region'))edited()});$('workspaceName').oninput=dirty;

async function projectRequest(url,body){if(!body&&(url.startsWith('/api/projects?')||url.startsWith('/api/workspace/drafts?'))&&url.includes('id='))url+='&references=1';const response=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error?.message||'저장소에 연결하지 못했습니다.');return data}
async function refreshLibrary(){try{libraryRecords=await projectRequest('/api/projects');renderLibrary()}catch(e){$('projectLibrary').textContent=e.message}}
function renderLibrary(){try{const items=libraryRecords,folders=[...new Set(items.map(x=>x.folder))].sort(),selected=$('folderFilter').value;$('folderFilter').innerHTML='<option value="">전체 폴더</option>'+folders.map(f=>'<option>'+esc(f)+'</option>').join('');if(folders.includes(selected))$('folderFilter').value=selected;$('folderNames').innerHTML=folders.map(f=>'<option value="'+esc(f)+'">').join('');const visible=items.filter(x=>workspaceMatches(x,{folder:$('folderFilter').value,search:$('projectSearch').value,status:$('projectStatus').value}));$('projectLibrary').innerHTML=visible.length?visible.map(p=>'<div class="library-row"><span><strong>'+esc(p.folder)+' / '+esc(p.name)+'</strong><small> · '+p.count+'장 · '+p.passed+'장 자동 통과 · '+(p.issues||0)+'장 수동 문제 · '+esc(new Date(p.updated).toLocaleString('ko-KR'))+'</small></span><button type="button" class="secondary small" data-open="'+p.id+'">열기</button><button type="button" class="ghost small" data-move="'+p.id+'">폴더 이동</button><button type="button" class="ghost small" data-delete="'+p.id+'">삭제</button></div>').join(''):'<p class="help">조건에 맞는 저장 작업이 없습니다. 검색어나 상태 필터를 바꿔 보세요.</p>';$('projectLibrary').querySelectorAll('[data-open]').forEach(b=>b.onclick=async()=>{if(W.busy||W.operation||S.controller)return;if(W.dirty&&!confirm('저장하지 않은 변경 사항이 있습니다. 다른 작업을 열까요?'))return;const unlock=lockWorkspace();try{const data=await projectRequest('/api/projects?id='+b.dataset.open);unlock();await loadWorkspace(new File([JSON.stringify(data)],'workspace.json'),true)}catch(e){error(e.message)}finally{unlock()}});$('projectLibrary').querySelectorAll('[data-move]').forEach(b=>b.onclick=async()=>{if(W.busy||W.operation||S.controller)return;W.movingProject=items.find(p=>p.id===b.dataset.move);$('folderMoveName').value=W.movingProject.folder;$('folderMoveError').textContent='';$('folderMoveDialog').showModal()});$('projectLibrary').querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(W.busy||W.operation||S.controller||!confirm('이 작업을 휴지통으로 이동할까요? 나중에 복원할 수 있습니다.'))return;const unlock=lockWorkspace();try{await projectRequest('/api/projects/delete',{id:b.dataset.delete});if(W.projectId===b.dataset.delete){W.projectId=null;dirty()}await refreshLibrary();await refreshTrash()}catch(e){error(e.message)}finally{unlock()}})}catch(e){$('projectLibrary').textContent=e.message}}
$('folderFilter').onchange=renderLibrary;$('workspaceFolder').oninput=dirty;
$('saveLocal').onclick=async()=>{if(W.busy||W.operation||S.controller)return error('분석이 끝난 뒤 저장하세요.');snapshot();if(!W.items.length)return error('저장할 이미지를 추가하세요.');const unlock=lockWorkspace();try{const items=await Promise.all(W.items.map(async item=>({...(await storedItem(item))})));const saved=await projectRequest('/api/projects',{format:'language-test-workspace',version:1,id:W.projectId,name:$('workspaceName').value,folder:$('workspaceFolder').value,items,batch:W.batch||null,watchPath:$('watchPath').value});W.projectId=saved.id;W.dirty=false;await clearDraft();$('workspaceStatus').textContent='앱에 저장했습니다 · '+new Date(saved.updated).toLocaleTimeString('ko-KR');await refreshLibrary()}catch(e){error('저장하지 못했습니다: '+e.message)}finally{unlock()}};
$('newWorkspace').onclick=async()=>{if(W.busy||W.operation||S.controller)return;if(W.dirty&&!confirm('저장하지 않은 변경 사항이 있습니다. 새 작업을 만들까요?'))return;await stopWatch();await saveDraft();W.items.forEach(x=>x.thumb&&URL.revokeObjectURL(x.thumb));W.items=[];W.active=null;W.batch=null;F.excelPlan=null;F.mapUndo=null;resetComparisonView();W.projectId=null;W.dirty=false;W.draftId=crypto.randomUUID();W.removed.forEach(x=>x.item.thumb&&URL.revokeObjectURL(x.item.thumb));W.removed=[];$('undoImage').disabled=true;stopRegion();resetResult();$('imageInput').value='';$('previewShell').classList.add('hidden');$('entries').replaceChildren();add();$('workspaceName').value='새 작업';$('workspaceStatus').textContent='이미지를 추가해 새 작업을 시작하세요.';$('statusFile').textContent='이미지 대기';queue()};


$('applyFolderMove').onclick=async()=>{
  if(W.busy||W.operation||S.controller||!W.movingProject)return;
  const project=W.movingProject,folder=$('folderMoveName').value.trim();
  if(!folder||folder.length>80){$('folderMoveError').textContent='폴더 이름을 1~80자로 입력하세요.';return}
  const unlock=lockWorkspace();try{await projectRequest('/api/projects/move',{id:project.id,folder});if(W.projectId===project.id)$('workspaceFolder').value=folder;await refreshLibrary();$('folderMoveDialog').close();$('workspaceStatus').textContent='저장한 작업을 '+folder+' 폴더로 이동했습니다.'}catch(e){$('folderMoveError').textContent=e.message}finally{unlock()}
};

window.addEventListener('beforeunload',event=>{if(W.dirty){event.preventDefault();event.returnValue=''}});
`;
